
fn assert_follow_up_requires_operator_input_contract(payload: &Value) {
    let requires_follow_up = payload
        .pointer("/routing/requires_follow_up")
        .and_then(Value::as_bool)
        .unwrap_or(false);
    let follow_up_owner = payload
        .pointer("/routing/follow_up_owner")
        .and_then(Value::as_str)
        .unwrap_or("none");
    let expected = requires_follow_up && follow_up_owner == "operator";
    assert_eq!(
        payload
            .pointer("/routing/follow_up_requires_operator_input")
            .and_then(Value::as_bool),
        Some(expected)
    );
}

#[test]
fn memory_kv_http_routes_round_trip_and_feed_context_pool() {
    let root = tempfile::tempdir().expect("tempdir");
    init_git_repo(root.path());
    let created = handle(
        root.path(),
        "POST",
        "/api/agents",
        br#"{"name":"Memory KV Probe","role":"analyst"}"#,
        &json!({"ok": true}),
    )
    .expect("create agent");
    let agent_id = clean_text(
        created
            .payload
            .get("agent_id")
            .and_then(Value::as_str)
            .unwrap_or(""),
        180,
    );
    assert!(!agent_id.is_empty());

    let set = handle(
        root.path(),
        "PUT",
        &format!("/api/memory/agents/{agent_id}/kv/focus.topic"),
        br#"{"value":"reliability"}"#,
        &json!({"ok": true}),
    )
    .expect("set memory kv");
    assert_eq!(set.status, 200);

    let listed = handle(
        root.path(),
        "GET",
        &format!("/api/memory/agents/{agent_id}/kv"),
        &[],
        &json!({"ok": true}),
    )
    .expect("list memory kv");
    assert_eq!(listed.status, 200);
    let keys = listed
        .payload
        .get("kv_pairs")
        .and_then(Value::as_array)
        .cloned()
        .unwrap_or_default()
        .iter()
        .filter_map(|row| row.get("key").and_then(Value::as_str))
        .map(|v| v.to_string())
        .collect::<Vec<_>>();
    assert!(keys.iter().any(|key| key == "focus.topic"));

    let got = handle(
        root.path(),
        "GET",
        &format!("/api/memory/agents/{agent_id}/kv/focus.topic"),
        &[],
        &json!({"ok": true}),
    )
    .expect("get memory kv");
    assert_eq!(got.status, 200);
    assert_eq!(
        got.payload.get("value").and_then(Value::as_str),
        Some("reliability")
    );

    let semantic = handle(
        root.path(),
        "GET",
        &format!("/api/memory/agents/{agent_id}/semantic-query?q=reliability&limit=4"),
        &[],
        &json!({"ok": true}),
    )
    .expect("semantic memory query");
    assert_eq!(semantic.status, 200);
    assert!(semantic
        .payload
        .get("matches")
        .and_then(Value::as_array)
        .map(|rows| !rows.is_empty())
        .unwrap_or(false));

    let message = handle(
        root.path(),
        "POST",
        &format!("/api/agents/{agent_id}/message"),
        br#"{"message":"Use stored memory if present."}"#,
        &json!({"ok": true}),
    )
    .expect("message with memory kv");
    assert_eq!(message.status, 200);
    assert!(
        message
            .payload
            .pointer("/context_pool/memory_kv_entries")
            .and_then(Value::as_i64)
            .unwrap_or(0)
            >= 1
    );

    let deleted = handle(
        root.path(),
        "DELETE",
        &format!("/api/memory/agents/{agent_id}/kv/focus.topic"),
        &[],
        &json!({"ok": true}),
    )
    .expect("delete memory kv");
    assert_eq!(deleted.status, 200);
    assert_eq!(
        deleted.payload.get("removed").and_then(Value::as_bool),
        Some(true)
    );
}

#[test]
fn agents_routes_terminal_and_artifact_endpoints_round_trip() {
    let root = tempfile::tempdir().expect("tempdir");
    let notes_dir = root.path().join("notes");
    let _ = fs::create_dir_all(&notes_dir);
    let _ = fs::write(notes_dir.join("plan.txt"), "ship it");
    let _ = fs::create_dir_all(notes_dir.join("sub"));
    let _ = fs::write(notes_dir.join("sub").join("extra.txt"), "plus one");

    let created = handle(
        root.path(),
        "POST",
        "/api/agents",
        br#"{"name":"Ops","role":"operator"}"#,
        &json!({"ok": true}),
    )
    .expect("create agent");
    let agent_id = clean_text(
        created
            .payload
            .get("agent_id")
            .and_then(Value::as_str)
            .unwrap_or(""),
        180,
    );
    assert!(!agent_id.is_empty());

    let file_read_missing_path = handle(
        root.path(),
        "POST",
        &format!("/api/agents/{agent_id}/file/read"),
        br#"{}"#,
        &json!({"ok": true}),
    )
    .expect("file read missing path");
    assert_follow_up_requires_operator_input_contract(&file_read_missing_path.payload);
    assert_eq!(file_read_missing_path.status, 400);
    assert_eq!(
        file_read_missing_path
            .payload
            .pointer("/routing/hint")
            .and_then(Value::as_str),
        Some("path_required")
    );
    assert_eq!(
        file_read_missing_path
            .payload
            .pointer("/routing/class")
            .and_then(Value::as_str),
        Some("path_repair")
    );
    assert_eq!(
        file_read_missing_path
            .payload
            .pointer("/routing/requires_binary_opt_in")
            .and_then(Value::as_bool),
        Some(false)
    );
    assert_eq!(
        file_read_missing_path
            .payload
            .pointer("/routing/requires_path_repair")
            .and_then(Value::as_bool),
        Some(true)
    );
    assert_eq!(
        file_read_missing_path
            .payload
            .pointer("/routing/requires_content_expansion")
            .and_then(Value::as_bool),
        Some(false)
    );
    assert_eq!(
        file_read_missing_path
            .payload
            .pointer("/routing/requires_mixed_follow_up")
            .and_then(Value::as_bool),
        Some(false)
    );
    assert_eq!(
        file_read_missing_path
            .payload
            .pointer("/routing/requires_partial_replay")
            .and_then(Value::as_bool),
        Some(false)
    );
    assert_eq!(
        file_read_missing_path
            .payload
            .pointer("/routing/blocker")
            .and_then(Value::as_str),
        Some("path_repair")
    );
    assert_eq!(
        file_read_missing_path
            .payload
            .pointer("/routing/binary_opt_in_blocked_count")
            .and_then(Value::as_u64),
        Some(0)
    );
    assert_eq!(
        file_read_missing_path
            .payload
            .pointer("/routing/requires_policy_repair")
            .and_then(Value::as_bool),
        Some(false)
    );
    assert_eq!(
        file_read_missing_path
            .payload
            .pointer("/routing/requires_follow_up")
            .and_then(Value::as_bool),
        Some(true)
    );
    assert_eq!(
        file_read_missing_path
            .payload
            .pointer("/routing/follow_up_can_auto_retry")
            .and_then(Value::as_bool),
        Some(false)
    );
    assert_eq!(
        file_read_missing_path
            .payload
            .pointer("/routing/follow_up_mode")
            .and_then(Value::as_str),
        Some("user_input")
    );
    assert_eq!(
        file_read_missing_path
            .payload
            .pointer("/routing/follow_up_task")
            .and_then(Value::as_str),
        Some("path_repair")
    );
    assert_eq!(
        file_read_missing_path
            .payload
            .pointer("/routing/follow_up_priority")
            .and_then(Value::as_str),
        Some("high")
    );
    assert_eq!(
        file_read_missing_path
            .payload
            .pointer("/routing/follow_up_blocking")
            .and_then(Value::as_bool),
        Some(true)
    );
    assert_eq!(
        file_read_missing_path
            .payload
            .pointer("/routing/follow_up_bucket")
            .and_then(Value::as_str),
        Some("blocking")
    );
    assert_eq!(
        file_read_missing_path
            .payload
            .pointer("/routing/follow_up_sla_seconds")
            .and_then(Value::as_u64),
        Some(30)
    );
    assert_eq!(
        file_read_missing_path
            .payload
            .pointer("/routing/follow_up_requires_immediate_action")
            .and_then(Value::as_bool),
        Some(true)
    );
    assert_eq!(
        file_read_missing_path
            .payload
            .pointer("/routing/follow_up_owner")
            .and_then(Value::as_str),
        Some("operator")
    );
    assert_eq!(
        file_read_missing_path
            .payload
            .pointer("/routing/follow_up_requires_confirmation")
            .and_then(Value::as_bool),
        Some(true)
    );
    assert_eq!(
        file_read_missing_path
            .payload
            .pointer("/routing/follow_up_action_kind")
            .and_then(Value::as_str),
        Some("repair")
    );
    assert_eq!(
        file_read_missing_path
            .payload
            .pointer("/routing/follow_up_requires_path_input")
            .and_then(Value::as_bool),
        Some(true)
    );
    assert_eq!(
        file_read_missing_path
            .payload
            .pointer("/routing/follow_up_can_defer")
            .and_then(Value::as_bool),
        Some(false)
    );
    assert_eq!(
        file_read_missing_path
            .payload
            .pointer("/routing/follow_up_requires_binary_opt_in_input")
            .and_then(Value::as_bool),
        Some(false)
    );
    assert_eq!(
        file_read_missing_path
            .payload
            .pointer("/routing/follow_up_requires_policy_repair_input")
            .and_then(Value::as_bool),
        Some(false)
    );
    assert_eq!(
        file_read_missing_path
            .payload
            .pointer("/routing/follow_up_requires_content_expansion_input")
            .and_then(Value::as_bool),
        Some(false)
    );
    assert_eq!(
        file_read_missing_path
            .payload
            .pointer("/routing/follow_up_requires_mixed_follow_up_input")
            .and_then(Value::as_bool),
        Some(false)
    );
    assert_eq!(
        file_read_missing_path
            .payload
            .pointer("/routing/follow_up_requires_partial_replay_input")
            .and_then(Value::as_bool),
        Some(false)
    );
    assert_eq!(
        file_read_missing_path
            .payload
            .pointer("/routing/follow_up_requires_user_text_input")
            .and_then(Value::as_bool),
        Some(true)
    );

    let file_read = handle(
        root.path(),
        "POST",
        &format!("/api/agents/{agent_id}/file/read"),
        br#"{"path":"notes/plan.txt"}"#,
        &json!({"ok": true}),
    )
    .expect("file read");
    assert_eq!(
        file_read
            .payload
            .pointer("/file/ok")
            .and_then(Value::as_bool),
        Some(true)
    );
    assert_eq!(
        file_read
            .payload
            .pointer("/file/content")
            .and_then(Value::as_str),
        Some("ship it")
    );
    assert_eq!(
        file_read
            .payload
            .pointer("/routing/hint")
            .and_then(Value::as_str),
        Some("text_primary")
    );
    let file_read_limited = handle(
        root.path(),
        "POST",
        &format!("/api/agents/{agent_id}/file/read"),
        br#"{"path":"notes/plan.txt","max_bytes":4}"#,
        &json!({"ok": true}),
    )
    .expect("file read limited");
    assert_follow_up_requires_operator_input_contract(&file_read_limited.payload);
    assert_eq!(
        file_read_limited
            .payload
            .pointer("/file/truncated")
            .and_then(Value::as_bool),
        Some(true)
    );
    assert_eq!(
        file_read_limited
            .payload
            .pointer("/routing/hint")
            .and_then(Value::as_str),
        Some("text_truncated")
    );
    assert_eq!(
        file_read_limited
            .payload
            .pointer("/routing/requires_content_expansion")
            .and_then(Value::as_bool),
        Some(true)
    );
    assert_eq!(
        file_read_limited
            .payload
            .pointer("/routing/requires_mixed_follow_up")
            .and_then(Value::as_bool),
        Some(false)
    );
    assert_eq!(
        file_read_limited
            .payload
            .pointer("/routing/requires_partial_replay")
            .and_then(Value::as_bool),
        Some(false)
    );
    assert_eq!(
        file_read_limited
            .payload
            .pointer("/routing/blocker")
            .and_then(Value::as_str),
        Some("content_expansion")
    );
    assert_eq!(
        file_read_limited
            .payload
            .pointer("/routing/binary_opt_in_blocked_count")
            .and_then(Value::as_u64),
        Some(0)
    );
    assert_eq!(
        file_read_limited
            .payload
            .pointer("/routing/requires_policy_repair")
            .and_then(Value::as_bool),
        Some(false)
    );
    assert_eq!(
        file_read_limited
            .payload
            .pointer("/routing/requires_follow_up")
            .and_then(Value::as_bool),
        Some(true)
    );
    assert_eq!(
        file_read_limited
            .payload
            .pointer("/routing/follow_up_can_auto_retry")
            .and_then(Value::as_bool),
        Some(true)
    );
    assert_eq!(
        file_read_limited
            .payload
            .pointer("/routing/follow_up_mode")
            .and_then(Value::as_str),
        Some("auto_retry")
    );
    assert_eq!(
        file_read_limited
            .payload
            .pointer("/routing/follow_up_task")
            .and_then(Value::as_str),
        Some("content_expansion")
    );
    assert_eq!(
        file_read_limited
            .payload
            .pointer("/routing/follow_up_priority")
            .and_then(Value::as_str),
        Some("low")
    );
    assert_eq!(
        file_read_limited
            .payload
            .pointer("/routing/follow_up_blocking")
            .and_then(Value::as_bool),
        Some(false)
    );
    assert_eq!(
        file_read_limited
            .payload
            .pointer("/routing/follow_up_bucket")
            .and_then(Value::as_str),
        Some("auto_retry")
    );
    assert_eq!(
        file_read_limited
            .payload
            .pointer("/routing/follow_up_sla_seconds")
            .and_then(Value::as_u64),
        Some(300)
    );
    assert_eq!(
        file_read_limited
            .payload
            .pointer("/routing/follow_up_requires_immediate_action")
            .and_then(Value::as_bool),
        Some(false)
    );
    assert_eq!(
        file_read_limited
            .payload
            .pointer("/routing/follow_up_owner")
            .and_then(Value::as_str),
        Some("system")
    );
    assert_eq!(
        file_read_limited
            .payload
            .pointer("/routing/follow_up_requires_confirmation")
            .and_then(Value::as_bool),
        Some(false)
    );
    assert_eq!(
        file_read_limited
            .payload
            .pointer("/routing/follow_up_action_kind")
            .and_then(Value::as_str),
        Some("retry")
    );
    assert_eq!(
        file_read_limited
            .payload
            .pointer("/routing/follow_up_requires_path_input")
            .and_then(Value::as_bool),
        Some(false)
    );
    assert_eq!(
        file_read_limited
            .payload
            .pointer("/routing/follow_up_can_defer")
            .and_then(Value::as_bool),
        Some(true)
    );
    assert_eq!(
        file_read_limited
            .payload
            .pointer("/routing/follow_up_requires_binary_opt_in_input")
            .and_then(Value::as_bool),
        Some(false)
    );
    assert_eq!(
        file_read_limited
            .payload
            .pointer("/routing/follow_up_requires_policy_repair_input")
            .and_then(Value::as_bool),
        Some(false)
    );
    assert_eq!(
        file_read_limited
            .payload
            .pointer("/routing/follow_up_requires_content_expansion_input")
            .and_then(Value::as_bool),
        Some(true)
    );
    assert_eq!(
        file_read_limited
            .payload
            .pointer("/routing/follow_up_requires_mixed_follow_up_input")
            .and_then(Value::as_bool),
        Some(false)
    );
    assert_eq!(
        file_read_limited
            .payload
            .pointer("/routing/follow_up_requires_partial_replay_input")
            .and_then(Value::as_bool),
        Some(false)
    );
    assert_eq!(
        file_read_limited
            .payload
            .pointer("/routing/follow_up_requires_user_text_input")
            .and_then(Value::as_bool),
        Some(false)
    );

    let file_read_full = handle(
        root.path(),
        "POST",
        &format!("/api/agents/{agent_id}/file/read"),
        br#"{"path":"notes/plan.txt","max_bytes":4,"full":true}"#,
        &json!({"ok": true}),
    )
    .expect("file read full");
    assert_follow_up_requires_operator_input_contract(&file_read_full.payload);
    assert_eq!(
        file_read_full
            .payload
            .pointer("/file/truncated")
            .and_then(Value::as_bool),
        Some(false)
    );
    assert_eq!(
        file_read_full
            .payload
            .pointer("/file/content")
            .and_then(Value::as_str),
        Some("ship it")
    );
    assert_eq!(
        file_read_full
            .payload
            .pointer("/routing/hint")
            .and_then(Value::as_str),
        Some("text_primary")
    );
    assert_eq!(
        file_read_full
            .payload
            .pointer("/routing/reason")
            .and_then(Value::as_str),
        Some("none")
    );
    assert_eq!(
        file_read_full
            .payload
            .pointer("/routing/retryable")
            .and_then(Value::as_bool),
        Some(false)
    );
    assert_eq!(
        file_read_full
            .payload
            .pointer("/routing/severity")
            .and_then(Value::as_str),
        Some("ok")
    );
    assert_eq!(
        file_read_full
            .payload
            .pointer("/routing/contract_version")
            .and_then(Value::as_str),
        Some("v1")
    );
    assert_eq!(
        file_read_full
            .payload
            .pointer("/routing/class")
            .and_then(Value::as_str),
        Some("none")
    );
    assert_eq!(
        file_read_full
            .payload
            .pointer("/routing/requires_binary_opt_in")
            .and_then(Value::as_bool),
        Some(false)
    );
    assert_eq!(
        file_read_full
            .payload
            .pointer("/routing/requires_path_repair")
            .and_then(Value::as_bool),
        Some(false)
    );
    assert_eq!(
        file_read_full
            .payload
            .pointer("/routing/requires_content_expansion")
            .and_then(Value::as_bool),
        Some(false)
    );
    assert_eq!(
        file_read_full
            .payload
            .pointer("/routing/requires_mixed_follow_up")
            .and_then(Value::as_bool),
        Some(false)
    );
    assert_eq!(
        file_read_full
            .payload
            .pointer("/routing/requires_partial_replay")
            .and_then(Value::as_bool),
        Some(false)
    );
    assert_eq!(
        file_read_full
            .payload
            .pointer("/routing/blocker")
            .and_then(Value::as_str),
        Some("none")
    );
    assert_eq!(
        file_read_full
            .payload
            .pointer("/routing/binary_opt_in_blocked_count")
            .and_then(Value::as_u64),
        Some(0)
    );
    assert_eq!(
        file_read_full
            .payload
            .pointer("/routing/requires_policy_repair")
            .and_then(Value::as_bool),
        Some(false)
    );
    assert_eq!(
        file_read_full
            .payload
            .pointer("/routing/requires_follow_up")
            .and_then(Value::as_bool),
        Some(false)
    );
    assert_eq!(
        file_read_full
            .payload
            .pointer("/routing/follow_up_can_auto_retry")
            .and_then(Value::as_bool),
        Some(false)
    );
    assert_eq!(
        file_read_full
            .payload
            .pointer("/routing/follow_up_mode")
            .and_then(Value::as_str),
        Some("none")
    );
    assert_eq!(
        file_read_full
            .payload
            .pointer("/routing/follow_up_task")
            .and_then(Value::as_str),
        Some("none")
    );
    assert_eq!(
        file_read_full
            .payload
            .pointer("/routing/follow_up_priority")
            .and_then(Value::as_str),
        Some("none")
    );
    assert_eq!(
        file_read_full
            .payload
            .pointer("/routing/follow_up_blocking")
            .and_then(Value::as_bool),
        Some(false)
    );
    assert_eq!(
        file_read_full
            .payload
            .pointer("/routing/follow_up_bucket")
            .and_then(Value::as_str),
        Some("none")
    );
    assert_eq!(
        file_read_full
            .payload
            .pointer("/routing/follow_up_sla_seconds")
            .and_then(Value::as_u64),
        Some(0)
    );
    assert_eq!(
        file_read_full
            .payload
            .pointer("/routing/follow_up_requires_immediate_action")
            .and_then(Value::as_bool),
        Some(false)
    );
    assert_eq!(
        file_read_full
            .payload
            .pointer("/routing/follow_up_owner")
            .and_then(Value::as_str),
        Some("none")
    );
    assert_eq!(
        file_read_full
            .payload
            .pointer("/routing/follow_up_requires_confirmation")
            .and_then(Value::as_bool),
        Some(false)
    );
    assert_eq!(
        file_read_full
            .payload
            .pointer("/routing/follow_up_action_kind")
            .and_then(Value::as_str),
        Some("none")
    );
    assert_eq!(
        file_read_full
            .payload
            .pointer("/routing/follow_up_requires_path_input")
            .and_then(Value::as_bool),
        Some(false)
    );
    assert_eq!(
        file_read_full
            .payload
            .pointer("/routing/follow_up_can_defer")
            .and_then(Value::as_bool),
        Some(false)
    );
    assert_eq!(
        file_read_full
            .payload
            .pointer("/routing/follow_up_requires_binary_opt_in_input")
            .and_then(Value::as_bool),
        Some(false)
    );
    assert_eq!(
        file_read_full
            .payload
            .pointer("/routing/follow_up_requires_policy_repair_input")
            .and_then(Value::as_bool),
        Some(false)
    );
    assert_eq!(
        file_read_full
            .payload
            .pointer("/routing/follow_up_requires_content_expansion_input")
            .and_then(Value::as_bool),
        Some(false)
    );
    assert_eq!(
        file_read_full
            .payload
            .pointer("/routing/follow_up_requires_mixed_follow_up_input")
            .and_then(Value::as_bool),
        Some(false)
    );
    assert_eq!(
        file_read_full
            .payload
            .pointer("/routing/follow_up_requires_partial_replay_input")
            .and_then(Value::as_bool),
        Some(false)
    );
    assert_eq!(
        file_read_full
            .payload
            .pointer("/routing/follow_up_requires_user_text_input")
            .and_then(Value::as_bool),
        Some(false)
    );
    assert_eq!(
        file_read_full
            .payload
            .pointer("/recovery/action")
            .and_then(Value::as_str),
        Some("none")
    );
    assert_eq!(
        file_read_full
            .payload
            .pointer("/recovery/retryable")
            .and_then(Value::as_bool),
        Some(false)
    );
    assert_eq!(
        file_read_full
            .payload
            .pointer("/recovery/class")
            .and_then(Value::as_str),
        Some("none")
    );
    assert_eq!(
        file_read_full
            .payload
            .pointer("/recovery/next_command")
            .and_then(Value::as_str),
        Some("none")
    );
    assert_eq!(
        file_read_full
            .payload
            .pointer("/recovery/requires_user_input")
            .and_then(Value::as_bool),
        Some(false)
    );

    let _ = fs::write(
        notes_dir.join("blob.bin"),
        vec![0_u8, 159, 10, 11, 12, 255, 0, 1, 2, 3],
    );
    let binary_blocked = handle(
        root.path(),
        "POST",
        &format!("/api/agents/{agent_id}/file/read"),
        br#"{"path":"notes/blob.bin"}"#,
        &json!({"ok": true}),
    )
    .expect("binary read blocked");
    assert_follow_up_requires_operator_input_contract(&binary_blocked.payload);
    assert_eq!(binary_blocked.status, 415);
    assert_eq!(
        binary_blocked.payload.get("error").and_then(Value::as_str),
        Some("binary_file_requires_opt_in")
    );
    assert_eq!(
        binary_blocked
            .payload
            .pointer("/routing/hint")
            .and_then(Value::as_str),
        Some("binary_opt_in_required")
    );
    assert_eq!(
        binary_blocked
            .payload
            .pointer("/routing/class")
            .and_then(Value::as_str),
        Some("binary_lane")
    );
    assert_eq!(
        binary_blocked
            .payload
            .pointer("/routing/requires_binary_opt_in")
            .and_then(Value::as_bool),
        Some(true)
    );
    assert_eq!(
        binary_blocked
            .payload
            .pointer("/routing/requires_path_repair")
            .and_then(Value::as_bool),
        Some(false)
    );
    assert_eq!(
        binary_blocked
            .payload
            .pointer("/routing/requires_content_expansion")
            .and_then(Value::as_bool),
        Some(false)
    );
    assert_eq!(
        binary_blocked
            .payload
            .pointer("/routing/requires_mixed_follow_up")
            .and_then(Value::as_bool),
        Some(false)
    );
    assert_eq!(
        binary_blocked
            .payload
            .pointer("/routing/requires_partial_replay")
            .and_then(Value::as_bool),
        Some(false)
    );
    assert_eq!(
        binary_blocked
            .payload
            .pointer("/routing/blocker")
            .and_then(Value::as_str),
        Some("binary_opt_in")
    );
    assert_eq!(
        binary_blocked
            .payload
            .pointer("/routing/binary_opt_in_blocked_count")
            .and_then(Value::as_u64),
        Some(1)
    );
    assert_eq!(
        binary_blocked
            .payload
            .pointer("/routing/requires_policy_repair")
            .and_then(Value::as_bool),
        Some(false)
    );
    assert_eq!(
        binary_blocked
            .payload
            .pointer("/routing/requires_follow_up")
            .and_then(Value::as_bool),
        Some(true)
    );
    assert_eq!(
        binary_blocked
            .payload
            .pointer("/routing/follow_up_can_auto_retry")
            .and_then(Value::as_bool),
        Some(true)
    );
    assert_eq!(
        binary_blocked
            .payload
            .pointer("/routing/follow_up_mode")
            .and_then(Value::as_str),
        Some("auto_retry")
    );
    assert_eq!(
        binary_blocked
            .payload
            .pointer("/routing/follow_up_task")
            .and_then(Value::as_str),
        Some("binary_opt_in")
    );
    assert_eq!(
        binary_blocked
            .payload
            .pointer("/routing/follow_up_priority")
            .and_then(Value::as_str),
        Some("high")
    );
    assert_eq!(
        binary_blocked
            .payload
            .pointer("/routing/follow_up_blocking")
            .and_then(Value::as_bool),
        Some(true)
    );
    assert_eq!(
        binary_blocked
            .payload
            .pointer("/routing/follow_up_bucket")
            .and_then(Value::as_str),
        Some("blocking")
    );
    assert_eq!(
        binary_blocked
            .payload
            .pointer("/routing/follow_up_sla_seconds")
            .and_then(Value::as_u64),
        Some(30)
    );
    assert_eq!(
        binary_blocked
            .payload
            .pointer("/routing/follow_up_requires_immediate_action")
            .and_then(Value::as_bool),
        Some(true)
    );
    assert_eq!(
        binary_blocked
            .payload
            .pointer("/routing/follow_up_owner")
            .and_then(Value::as_str),
        Some("system")
    );
    assert_eq!(
        binary_blocked
            .payload
            .pointer("/routing/follow_up_requires_confirmation")
            .and_then(Value::as_bool),
        Some(false)
    );
    assert_eq!(
        binary_blocked
            .payload
            .pointer("/routing/follow_up_action_kind")
            .and_then(Value::as_str),
        Some("retry")
    );
    assert_eq!(
        binary_blocked
            .payload
            .pointer("/routing/follow_up_requires_path_input")
            .and_then(Value::as_bool),
        Some(false)
    );
    assert_eq!(
        binary_blocked
            .payload
            .pointer("/routing/follow_up_can_defer")
            .and_then(Value::as_bool),
        Some(false)
    );
    assert_eq!(
        binary_blocked
            .payload
            .pointer("/routing/follow_up_requires_binary_opt_in_input")
            .and_then(Value::as_bool),
        Some(true)
    );
    assert_eq!(
        binary_blocked
            .payload
            .pointer("/routing/follow_up_requires_policy_repair_input")
            .and_then(Value::as_bool),
        Some(false)
    );
    assert_eq!(
        binary_blocked
            .payload
            .pointer("/routing/follow_up_requires_content_expansion_input")
            .and_then(Value::as_bool),
        Some(false)
    );
    assert_eq!(
        binary_blocked
            .payload
            .pointer("/routing/follow_up_requires_mixed_follow_up_input")
            .and_then(Value::as_bool),
        Some(false)
    );
    assert_eq!(
        binary_blocked
            .payload
            .pointer("/routing/follow_up_requires_partial_replay_input")
            .and_then(Value::as_bool),
        Some(false)
    );
    assert_eq!(
        binary_blocked
            .payload
            .pointer("/routing/follow_up_requires_user_text_input")
            .and_then(Value::as_bool),
        Some(false)
    );
    assert_eq!(
        binary_blocked
            .payload
            .pointer("/routing/reason")
            .and_then(Value::as_str),
        Some("binary_opt_in_missing")
    );
    assert_eq!(
        binary_blocked
            .payload
            .pointer("/routing/retryable")
            .and_then(Value::as_bool),
        Some(true)
    );
    assert_eq!(
        binary_blocked
            .payload
            .pointer("/routing/severity")
            .and_then(Value::as_str),
        Some("error")
    );
    assert_eq!(
        binary_blocked
            .payload
            .pointer("/routing/contract_version")
            .and_then(Value::as_str),
        Some("v1")
    );
    assert_eq!(
        binary_blocked
            .payload
            .pointer("/recovery/action")
            .and_then(Value::as_str),
        Some("retry_with_allow_binary_true")
    );
    assert_eq!(
        binary_blocked
            .payload
            .pointer("/recovery/retryable")
            .and_then(Value::as_bool),
        Some(true)
    );
    assert_eq!(
        binary_blocked
            .payload
            .pointer("/recovery/class")
            .and_then(Value::as_str),
        Some("binary_opt_in")
    );
    assert_eq!(
        binary_blocked
            .payload
            .pointer("/recovery/next_command")
            .and_then(Value::as_str),
        Some("file_read")
    );
    assert_eq!(
        binary_blocked
            .payload
            .pointer("/recovery/requires_user_input")
            .and_then(Value::as_bool),
        Some(false)
    );

    let binary_allowed = handle(
        root.path(),
        "POST",
        &format!("/api/agents/{agent_id}/file/read"),
        br#"{"path":"notes/blob.bin","allow_binary":true,"max_bytes":8}"#,
        &json!({"ok": true}),
    )
    .expect("binary read allowed");
    assert_eq!(binary_allowed.status, 200);
    assert_eq!(
        binary_allowed
            .payload
            .pointer("/file/binary")
            .and_then(Value::as_bool),
        Some(true)
    );
    assert_eq!(
        binary_allowed
            .payload
            .pointer("/routing/hint")
            .and_then(Value::as_str),
        Some("binary_primary")
    );
    assert_eq!(
        binary_allowed
            .payload
            .pointer("/routing/class")
            .and_then(Value::as_str),
        Some("binary_lane")
    );
    assert_eq!(
        binary_allowed
            .payload
            .pointer("/routing/requires_binary_opt_in")
            .and_then(Value::as_bool),
        Some(false)
    );
    assert_eq!(
        binary_allowed
            .payload
            .pointer("/routing/requires_path_repair")
            .and_then(Value::as_bool),
        Some(false)
    );
    assert_eq!(
        binary_allowed
            .payload
            .pointer("/routing/requires_content_expansion")
            .and_then(Value::as_bool),
        Some(false)
    );
    assert_eq!(
        binary_allowed
            .payload
            .pointer("/routing/requires_mixed_follow_up")
            .and_then(Value::as_bool),
        Some(false)
    );
    assert_eq!(
        binary_allowed
            .payload
            .pointer("/routing/requires_partial_replay")
            .and_then(Value::as_bool),
        Some(false)
    );
    assert_eq!(
        binary_allowed
            .payload
            .pointer("/routing/blocker")
            .and_then(Value::as_str),
        Some("none")
    );
    assert_eq!(
        binary_allowed
            .payload
            .pointer("/routing/binary_opt_in_blocked_count")
            .and_then(Value::as_u64),
        Some(0)
    );
    assert_eq!(
        binary_allowed
            .payload
            .pointer("/routing/requires_policy_repair")
            .and_then(Value::as_bool),
        Some(false)
    );
    assert_eq!(
        binary_allowed
            .payload
            .pointer("/routing/requires_follow_up")
            .and_then(Value::as_bool),
        Some(false)
    );
    assert_eq!(
        binary_allowed
            .payload
            .pointer("/routing/follow_up_can_auto_retry")
            .and_then(Value::as_bool),
        Some(false)
    );
    assert_eq!(
        binary_allowed
            .payload
            .pointer("/routing/follow_up_mode")
            .and_then(Value::as_str),
        Some("none")
    );
    assert_eq!(
        binary_allowed
            .payload
            .pointer("/routing/follow_up_task")
            .and_then(Value::as_str),
        Some("none")
    );
    assert_eq!(
        binary_allowed
            .payload
            .pointer("/routing/follow_up_priority")
            .and_then(Value::as_str),
        Some("none")
    );
    assert_eq!(
        binary_allowed
            .payload
            .pointer("/routing/follow_up_blocking")
            .and_then(Value::as_bool),
        Some(false)
    );
    assert_eq!(
        binary_allowed
            .payload
            .pointer("/routing/follow_up_bucket")
            .and_then(Value::as_str),
        Some("none")
    );
    assert_eq!(
        binary_allowed
            .payload
            .pointer("/routing/follow_up_sla_seconds")
            .and_then(Value::as_u64),
        Some(0)
    );
    assert_eq!(
        binary_allowed
            .payload
            .pointer("/routing/follow_up_requires_immediate_action")
            .and_then(Value::as_bool),
        Some(false)
    );
    assert_eq!(
        binary_allowed
            .payload
            .pointer("/routing/follow_up_owner")
            .and_then(Value::as_str),
        Some("none")
    );
    assert_eq!(
        binary_allowed
            .payload
            .pointer("/routing/follow_up_requires_confirmation")
            .and_then(Value::as_bool),
        Some(false)
    );
    assert_eq!(
        binary_allowed
            .payload
            .pointer("/routing/follow_up_action_kind")
            .and_then(Value::as_str),
        Some("none")
    );
    assert_eq!(
        binary_allowed
            .payload
            .pointer("/routing/follow_up_requires_path_input")
            .and_then(Value::as_bool),
        Some(false)
    );
    assert_eq!(
        binary_allowed
            .payload
            .pointer("/routing/follow_up_can_defer")
            .and_then(Value::as_bool),
        Some(false)
    );
    assert_eq!(
        binary_allowed
            .payload
            .pointer("/routing/follow_up_requires_binary_opt_in_input")
            .and_then(Value::as_bool),
        Some(false)
    );
    assert_eq!(
        binary_allowed
            .payload
            .pointer("/routing/follow_up_requires_policy_repair_input")
            .and_then(Value::as_bool),
        Some(false)
    );
    assert_eq!(
        binary_allowed
            .payload
            .pointer("/routing/follow_up_requires_content_expansion_input")
            .and_then(Value::as_bool),
        Some(false)
    );
    assert_eq!(
        binary_allowed
            .payload
            .pointer("/routing/follow_up_requires_mixed_follow_up_input")
            .and_then(Value::as_bool),
        Some(false)
    );
    assert_eq!(
        binary_allowed
            .payload
            .pointer("/routing/follow_up_requires_partial_replay_input")
            .and_then(Value::as_bool),
        Some(false)
    );
    assert_eq!(
        binary_allowed
            .payload
            .pointer("/routing/follow_up_requires_user_text_input")
            .and_then(Value::as_bool),
        Some(false)
    );
    assert_eq!(
        binary_allowed
            .payload
            .pointer("/routing/reason")
            .and_then(Value::as_str),
        Some("none")
    );
    assert_eq!(
        binary_allowed
            .payload
            .pointer("/routing/retryable")
            .and_then(Value::as_bool),
        Some(false)
    );
    assert_eq!(
        binary_allowed
            .payload
            .pointer("/recovery/action")
            .and_then(Value::as_str),
        Some("none")
    );
    assert_eq!(
        binary_allowed
            .payload
            .pointer("/recovery/retryable")
            .and_then(Value::as_bool),
        Some(false)
    );
    assert_eq!(
        binary_allowed
            .payload
            .pointer("/recovery/class")
            .and_then(Value::as_str),
        Some("none")
    );
    assert_eq!(
        binary_allowed
            .payload
            .pointer("/recovery/next_command")
            .and_then(Value::as_str),
        Some("none")
    );
    assert_eq!(
        binary_allowed
            .payload
            .pointer("/recovery/requires_user_input")
            .and_then(Value::as_bool),
        Some(false)
    );
    assert!(!binary_allowed
        .payload
        .pointer("/file/content_base64")
        .and_then(Value::as_str)
        .unwrap_or("")
        .is_empty());

    let file_read_many = handle(
        root.path(),
        "POST",
        &format!("/api/agents/{agent_id}/file/read-many"),
        br#"{"paths":["notes/plan.txt","notes/blob.bin"],"allow_binary":false,"max_bytes":16}"#,
        &json!({"ok": true}),
    )
    .expect("file read many");
    assert_follow_up_requires_operator_input_contract(&file_read_many.payload);
    assert_eq!(file_read_many.status, 200);
    assert_eq!(file_read_many.payload.pointer("/counts/ok").and_then(Value::as_u64), Some(1));
    assert_eq!(file_read_many.payload.pointer("/counts/failed").and_then(Value::as_u64), Some(1));
    assert_eq!(
        file_read_many
            .payload
            .pointer("/counts/group_failed")
            .and_then(Value::as_u64),
        Some(1)
    );
    assert_eq!(file_read_many.payload.pointer("/files/0/content").and_then(Value::as_str), Some("ship it"));
    assert_eq!(file_read_many.payload.pointer("/failed/0/error").and_then(Value::as_str), Some("binary_file_requires_opt_in"));
    assert_eq!(file_read_many.payload.pointer("/counts/text").and_then(Value::as_u64), Some(1));
    assert_eq!(file_read_many.payload.pointer("/counts/binary").and_then(Value::as_u64), Some(1));
    assert_eq!(
        file_read_many
            .payload
            .pointer("/routing/hint")
            .and_then(Value::as_str),
        Some("mixed_text_binary_follow_up")
    );
    assert_eq!(
        file_read_many
            .payload
            .pointer("/routing/class")
            .and_then(Value::as_str),
        Some("binary_lane")
    );
    assert_eq!(
        file_read_many
            .payload
            .pointer("/routing/requires_binary_opt_in")
            .and_then(Value::as_bool),
        Some(true)
    );
    assert_eq!(
        file_read_many
            .payload
            .pointer("/routing/requires_path_repair")
            .and_then(Value::as_bool),
        Some(false)
    );
    assert_eq!(
        file_read_many
            .payload
            .pointer("/routing/requires_content_expansion")
            .and_then(Value::as_bool),
        Some(false)
    );
    assert_eq!(
        file_read_many
            .payload
            .pointer("/routing/requires_mixed_follow_up")
            .and_then(Value::as_bool),
        Some(true)
    );
    assert_eq!(
        file_read_many
            .payload
            .pointer("/routing/requires_partial_replay")
            .and_then(Value::as_bool),
        Some(true)
    );
    assert_eq!(
        file_read_many
            .payload
            .pointer("/routing/blocker")
            .and_then(Value::as_str),
        Some("binary_opt_in")
    );
    assert_eq!(
        file_read_many
            .payload
            .pointer("/routing/binary_opt_in_blocked_count")
            .and_then(Value::as_u64),
        Some(1)
    );
    assert_eq!(
        file_read_many
            .payload
            .pointer("/routing/requires_policy_repair")
            .and_then(Value::as_bool),
        Some(false)
    );
    assert_eq!(
        file_read_many
            .payload
            .pointer("/routing/requires_follow_up")
            .and_then(Value::as_bool),
        Some(true)
    );
    assert_eq!(
        file_read_many
            .payload
            .pointer("/routing/follow_up_can_auto_retry")
            .and_then(Value::as_bool),
        Some(true)
    );
    assert_eq!(
        file_read_many
            .payload
            .pointer("/routing/follow_up_mode")
            .and_then(Value::as_str),
        Some("auto_retry")
    );
    assert_eq!(
        file_read_many
            .payload
            .pointer("/routing/follow_up_task")
            .and_then(Value::as_str),
        Some("binary_opt_in")
    );
    assert_eq!(
        file_read_many
            .payload
            .pointer("/routing/follow_up_priority")
            .and_then(Value::as_str),
        Some("high")
    );
    assert_eq!(
        file_read_many
            .payload
            .pointer("/routing/follow_up_blocking")
            .and_then(Value::as_bool),
        Some(true)
    );
    assert_eq!(
        file_read_many
            .payload
            .pointer("/routing/follow_up_bucket")
            .and_then(Value::as_str),
        Some("blocking")
    );
    assert_eq!(
        file_read_many
            .payload
            .pointer("/routing/follow_up_sla_seconds")
            .and_then(Value::as_u64),
        Some(30)
    );
    assert_eq!(
        file_read_many
            .payload
            .pointer("/routing/follow_up_requires_immediate_action")
            .and_then(Value::as_bool),
        Some(true)
    );
    assert_eq!(
        file_read_many
            .payload
            .pointer("/routing/follow_up_owner")
            .and_then(Value::as_str),
        Some("system")
    );
    assert_eq!(
        file_read_many
            .payload
            .pointer("/routing/follow_up_requires_confirmation")
            .and_then(Value::as_bool),
        Some(false)
    );
    assert_eq!(
        file_read_many
            .payload
            .pointer("/routing/follow_up_action_kind")
            .and_then(Value::as_str),
        Some("retry")
    );
    assert_eq!(
        file_read_many
            .payload
            .pointer("/routing/follow_up_requires_path_input")
            .and_then(Value::as_bool),
        Some(false)
    );
    assert_eq!(
        file_read_many
            .payload
            .pointer("/routing/follow_up_can_defer")
            .and_then(Value::as_bool),
        Some(false)
    );
    assert_eq!(
        file_read_many
            .payload
            .pointer("/routing/follow_up_requires_binary_opt_in_input")
            .and_then(Value::as_bool),
        Some(true)
    );
    assert_eq!(
        file_read_many
            .payload
            .pointer("/routing/follow_up_requires_policy_repair_input")
            .and_then(Value::as_bool),
        Some(false)
    );
    assert_eq!(
        file_read_many
            .payload
            .pointer("/routing/follow_up_requires_content_expansion_input")
            .and_then(Value::as_bool),
        Some(false)
    );
    assert_eq!(
        file_read_many
            .payload
            .pointer("/routing/follow_up_requires_mixed_follow_up_input")
            .and_then(Value::as_bool),
        Some(true)
    );
    assert_eq!(
        file_read_many
            .payload
            .pointer("/routing/follow_up_requires_partial_replay_input")
            .and_then(Value::as_bool),
        Some(true)
    );
    assert_eq!(
        file_read_many
            .payload
            .pointer("/routing/follow_up_requires_user_text_input")
            .and_then(Value::as_bool),
        Some(false)
    );
    assert_eq!(
        file_read_many
            .payload
            .pointer("/counts/truncated")
            .and_then(Value::as_u64),
        Some(0)
    );
    assert_eq!(
        file_read_many
            .payload
            .pointer("/counts/binary_opt_in_blocked")
            .and_then(Value::as_u64),
        Some(1)
    );
    assert_eq!(
        file_read_many
            .payload
            .pointer("/counts/group_binary_opt_in_blocked")
            .and_then(Value::as_u64),
        Some(1)
    );
    assert_eq!(
        file_read_many
            .payload
            .pointer("/groups/binary_opt_in_blocked")
            .and_then(Value::as_array)
            .map(|rows| rows.len()),
        Some(1)
    );
    assert_eq!(
        file_read_many
            .payload
            .pointer("/routing/reason")
            .and_then(Value::as_str),
        Some("binary_entries_pending_opt_in")
    );
    assert_eq!(
        file_read_many
            .payload
            .pointer("/routing/retryable")
            .and_then(Value::as_bool),
        Some(true)
    );
    assert_eq!(
        file_read_many
            .payload
            .pointer("/routing/severity")
            .and_then(Value::as_str),
        Some("degraded")
    );
    assert_eq!(
        file_read_many
            .payload
            .pointer("/routing/contract_version")
            .and_then(Value::as_str),
        Some("v1")
    );
    assert_eq!(
        file_read_many
            .payload
            .pointer("/recovery/action")
            .and_then(Value::as_str),
        Some("review_text_then_opt_in_binary")
    );
    assert_eq!(
        file_read_many
            .payload
            .pointer("/recovery/retryable")
            .and_then(Value::as_bool),
        Some(true)
    );
    assert_eq!(
        file_read_many
            .payload
            .pointer("/recovery/class")
            .and_then(Value::as_str),
        Some("binary_opt_in")
    );
    assert_eq!(
        file_read_many
            .payload
            .pointer("/recovery/next_command")
            .and_then(Value::as_str),
        Some("file_read_many")
    );
    assert_eq!(
        file_read_many
            .payload
            .pointer("/recovery/requires_user_input")
            .and_then(Value::as_bool),
        Some(false)
    );
    assert_eq!(
        file_read_many
            .payload
            .pointer("/groups/text/0")
            .and_then(Value::as_str)
            .unwrap_or("")
            .contains("plan.txt"),
        true
    );
    assert!(
        file_read_many
            .payload
            .pointer("/groups/failed/0")
            .and_then(Value::as_str)
            .unwrap_or("")
            .contains("blob.bin")
    );

    let file_read_many_binary = handle(
        root.path(),
        "POST",
        &format!("/api/agents/{agent_id}/file/read-many"),
        br#"{"paths":["notes/blob.bin"],"allow_binary":true,"max_bytes":8}"#,
        &json!({"ok": true}),
    )
    .expect("file read many binary");
    assert_eq!(file_read_many_binary.status, 200);
    assert_eq!(file_read_many_binary.payload.pointer("/counts/ok").and_then(Value::as_u64), Some(1));
    assert!(!file_read_many_binary
        .payload
        .pointer("/files/0/content_base64")
        .and_then(Value::as_str)
        .unwrap_or("")
        .is_empty());
    assert_eq!(file_read_many_binary.payload.pointer("/counts/binary").and_then(Value::as_u64), Some(1));
    assert_eq!(
        file_read_many_binary
            .payload
            .pointer("/routing/hint")
            .and_then(Value::as_str),
        Some("binary_primary")
    );
    assert_eq!(
        file_read_many_binary
            .payload
            .pointer("/routing/class")
            .and_then(Value::as_str),
        Some("binary_lane")
    );
    assert_eq!(
        file_read_many_binary
            .payload
            .pointer("/routing/requires_binary_opt_in")
            .and_then(Value::as_bool),
        Some(false)
    );
    assert_eq!(
        file_read_many_binary
            .payload
            .pointer("/routing/requires_path_repair")
            .and_then(Value::as_bool),
        Some(false)
    );
    assert_eq!(
        file_read_many_binary
            .payload
            .pointer("/routing/requires_content_expansion")
            .and_then(Value::as_bool),
        Some(false)
    );
    assert_eq!(
        file_read_many_binary
            .payload
            .pointer("/routing/requires_mixed_follow_up")
            .and_then(Value::as_bool),
        Some(false)
    );
    assert_eq!(
        file_read_many_binary
            .payload
            .pointer("/routing/requires_partial_replay")
            .and_then(Value::as_bool),
        Some(false)
    );
    assert_eq!(
        file_read_many_binary
            .payload
            .pointer("/routing/blocker")
            .and_then(Value::as_str),
        Some("none")
    );
    assert_eq!(
        file_read_many_binary
            .payload
            .pointer("/routing/binary_opt_in_blocked_count")
            .and_then(Value::as_u64),
        Some(0)
    );
    assert_eq!(
        file_read_many_binary
            .payload
            .pointer("/routing/requires_policy_repair")
            .and_then(Value::as_bool),
        Some(false)
    );
    assert_eq!(
        file_read_many_binary
            .payload
            .pointer("/routing/requires_follow_up")
            .and_then(Value::as_bool),
        Some(false)
    );
    assert_eq!(
        file_read_many_binary
            .payload
            .pointer("/routing/follow_up_can_auto_retry")
            .and_then(Value::as_bool),
        Some(false)
    );
    assert_eq!(
        file_read_many_binary
            .payload
            .pointer("/routing/follow_up_mode")
            .and_then(Value::as_str),
        Some("none")
    );
    assert_eq!(
        file_read_many_binary
            .payload
            .pointer("/routing/follow_up_task")
            .and_then(Value::as_str),
        Some("none")
    );
    assert_eq!(
        file_read_many_binary
            .payload
            .pointer("/routing/follow_up_priority")
            .and_then(Value::as_str),
        Some("none")
    );
    assert_eq!(
        file_read_many_binary
            .payload
            .pointer("/routing/follow_up_blocking")
            .and_then(Value::as_bool),
        Some(false)
    );
    assert_eq!(
        file_read_many_binary
            .payload
            .pointer("/routing/follow_up_bucket")
            .and_then(Value::as_str),
        Some("none")
    );
    assert_eq!(
        file_read_many_binary
            .payload
            .pointer("/routing/follow_up_sla_seconds")
            .and_then(Value::as_u64),
        Some(0)
    );
    assert_eq!(
        file_read_many_binary
            .payload
            .pointer("/routing/follow_up_requires_immediate_action")
            .and_then(Value::as_bool),
        Some(false)
    );
    assert_eq!(
        file_read_many_binary
            .payload
            .pointer("/routing/follow_up_owner")
            .and_then(Value::as_str),
        Some("none")
    );
    assert_eq!(
        file_read_many_binary
            .payload
            .pointer("/routing/follow_up_requires_confirmation")
            .and_then(Value::as_bool),
        Some(false)
    );
    assert_eq!(
        file_read_many_binary
            .payload
            .pointer("/routing/follow_up_action_kind")
            .and_then(Value::as_str),
        Some("none")
    );
    assert_eq!(
        file_read_many_binary
            .payload
            .pointer("/routing/follow_up_requires_path_input")
            .and_then(Value::as_bool),
        Some(false)
    );
    assert_eq!(
        file_read_many_binary
            .payload
            .pointer("/routing/follow_up_can_defer")
            .and_then(Value::as_bool),
        Some(false)
    );
    assert_eq!(
        file_read_many_binary
            .payload
            .pointer("/routing/follow_up_requires_binary_opt_in_input")
            .and_then(Value::as_bool),
        Some(false)
    );
    assert_eq!(
        file_read_many_binary
            .payload
            .pointer("/routing/follow_up_requires_policy_repair_input")
            .and_then(Value::as_bool),
        Some(false)
    );
    assert_eq!(
        file_read_many_binary
            .payload
            .pointer("/routing/follow_up_requires_content_expansion_input")
            .and_then(Value::as_bool),
        Some(false)
    );
    assert_eq!(
        file_read_many_binary
            .payload
            .pointer("/routing/follow_up_requires_mixed_follow_up_input")
            .and_then(Value::as_bool),
        Some(false)
    );
    assert_eq!(
        file_read_many_binary
            .payload
            .pointer("/routing/follow_up_requires_partial_replay_input")
            .and_then(Value::as_bool),
        Some(false)
    );
    assert_eq!(
        file_read_many_binary
            .payload
            .pointer("/routing/follow_up_requires_user_text_input")
            .and_then(Value::as_bool),
        Some(false)
    );
    assert_eq!(
        file_read_many_binary
            .payload
            .pointer("/counts/truncated")
            .and_then(Value::as_u64),
        Some(0)
    );
    assert_eq!(
        file_read_many_binary
            .payload
            .pointer("/counts/binary_opt_in_blocked")
            .and_then(Value::as_u64),
        Some(0)
    );
    assert_eq!(
        file_read_many_binary
            .payload
            .pointer("/routing/reason")
            .and_then(Value::as_str),
        Some("none")
    );
    assert_eq!(
        file_read_many_binary
            .payload
            .pointer("/routing/retryable")
            .and_then(Value::as_bool),
        Some(false)
    );
    assert_eq!(
        file_read_many_binary
            .payload
            .pointer("/routing/severity")
            .and_then(Value::as_str),
        Some("ok")
    );
    assert_eq!(
        file_read_many_binary
            .payload
            .pointer("/routing/contract_version")
            .and_then(Value::as_str),
        Some("v1")
    );
    assert_eq!(
        file_read_many_binary
            .payload
            .pointer("/recovery/action")
            .and_then(Value::as_str),
        Some("none")
    );
    assert_eq!(
        file_read_many_binary
            .payload
            .pointer("/recovery/retryable")
            .and_then(Value::as_bool),
        Some(false)
    );
    assert_eq!(
        file_read_many_binary
            .payload
            .pointer("/recovery/class")
            .and_then(Value::as_str),
        Some("none")
    );
    assert_eq!(
        file_read_many_binary
            .payload
            .pointer("/recovery/next_command")
            .and_then(Value::as_str),
        Some("none")
    );
    assert_eq!(
        file_read_many_binary
            .payload
            .pointer("/recovery/requires_user_input")
            .and_then(Value::as_bool),
        Some(false)
    );

    let file_read_many_missing = handle(
        root.path(),
        "POST",
        &format!("/api/agents/{agent_id}/file/read-many"),
        br#"{"paths":["notes/missing.txt"]}"#,
        &json!({"ok": true}),
    )
    .expect("file read many missing");
    assert_follow_up_requires_operator_input_contract(&file_read_many_missing.payload);
    assert_eq!(
        file_read_many_missing
            .payload
            .pointer("/routing/hint")
            .and_then(Value::as_str),
        Some("path_repair_required")
    );
    assert_eq!(
        file_read_many_missing
            .payload
            .pointer("/routing/class")
            .and_then(Value::as_str),
        Some("path_repair")
    );
    assert_eq!(
        file_read_many_missing
            .payload
            .pointer("/routing/requires_binary_opt_in")
            .and_then(Value::as_bool),
        Some(false)
    );
    assert_eq!(
        file_read_many_missing
            .payload
            .pointer("/routing/requires_path_repair")
            .and_then(Value::as_bool),
        Some(true)
    );
    assert_eq!(
        file_read_many_missing
            .payload
            .pointer("/routing/requires_content_expansion")
            .and_then(Value::as_bool),
        Some(false)
    );
    assert_eq!(
        file_read_many_missing
            .payload
            .pointer("/routing/requires_mixed_follow_up")
            .and_then(Value::as_bool),
        Some(false)
    );
    assert_eq!(
        file_read_many_missing
            .payload
            .pointer("/routing/requires_partial_replay")
            .and_then(Value::as_bool),
        Some(false)
    );
    assert_eq!(
        file_read_many_missing
            .payload
            .pointer("/routing/blocker")
            .and_then(Value::as_str),
        Some("path_repair")
    );
    assert_eq!(
        file_read_many_missing
            .payload
            .pointer("/routing/binary_opt_in_blocked_count")
            .and_then(Value::as_u64),
        Some(0)
    );
    assert_eq!(
        file_read_many_missing
            .payload
            .pointer("/routing/requires_policy_repair")
            .and_then(Value::as_bool),
        Some(false)
    );
    assert_eq!(
        file_read_many_missing
            .payload
            .pointer("/routing/requires_follow_up")
            .and_then(Value::as_bool),
        Some(true)
    );
    assert_eq!(
        file_read_many_missing
            .payload
            .pointer("/routing/follow_up_can_auto_retry")
            .and_then(Value::as_bool),
        Some(false)
    );
    assert_eq!(
        file_read_many_missing
            .payload
            .pointer("/routing/follow_up_mode")
            .and_then(Value::as_str),
        Some("user_input")
    );
    assert_eq!(
        file_read_many_missing
            .payload
            .pointer("/routing/follow_up_task")
            .and_then(Value::as_str),
        Some("path_repair")
    );
    assert_eq!(
        file_read_many_missing
            .payload
            .pointer("/routing/follow_up_priority")
            .and_then(Value::as_str),
        Some("high")
    );
    assert_eq!(
        file_read_many_missing
            .payload
            .pointer("/routing/follow_up_blocking")
            .and_then(Value::as_bool),
        Some(true)
    );
    assert_eq!(
        file_read_many_missing
            .payload
            .pointer("/routing/follow_up_bucket")
            .and_then(Value::as_str),
        Some("blocking")
    );
    assert_eq!(
        file_read_many_missing
            .payload
            .pointer("/routing/follow_up_sla_seconds")
            .and_then(Value::as_u64),
        Some(30)
    );
    assert_eq!(
        file_read_many_missing
            .payload
            .pointer("/routing/follow_up_requires_immediate_action")
            .and_then(Value::as_bool),
        Some(true)
    );
    assert_eq!(
        file_read_many_missing
            .payload
            .pointer("/routing/follow_up_owner")
            .and_then(Value::as_str),
        Some("operator")
    );
    assert_eq!(
        file_read_many_missing
            .payload
            .pointer("/routing/follow_up_requires_confirmation")
            .and_then(Value::as_bool),
        Some(true)
    );
    assert_eq!(
        file_read_many_missing
            .payload
            .pointer("/routing/follow_up_action_kind")
            .and_then(Value::as_str),
        Some("repair")
    );
    assert_eq!(
        file_read_many_missing
            .payload
            .pointer("/routing/follow_up_requires_path_input")
            .and_then(Value::as_bool),
        Some(true)
    );
    assert_eq!(
        file_read_many_missing
            .payload
            .pointer("/routing/follow_up_can_defer")
            .and_then(Value::as_bool),
        Some(false)
    );
    assert_eq!(
        file_read_many_missing
            .payload
            .pointer("/routing/follow_up_requires_binary_opt_in_input")
            .and_then(Value::as_bool),
        Some(false)
    );
    assert_eq!(
        file_read_many_missing
            .payload
            .pointer("/routing/follow_up_requires_policy_repair_input")
            .and_then(Value::as_bool),
        Some(false)
    );
    assert_eq!(
        file_read_many_missing
            .payload
            .pointer("/routing/follow_up_requires_content_expansion_input")
            .and_then(Value::as_bool),
        Some(false)
    );
    assert_eq!(
        file_read_many_missing
            .payload
            .pointer("/routing/follow_up_requires_mixed_follow_up_input")
            .and_then(Value::as_bool),
        Some(false)
    );
    assert_eq!(
        file_read_many_missing
            .payload
            .pointer("/routing/follow_up_requires_partial_replay_input")
            .and_then(Value::as_bool),
        Some(false)
    );
    assert_eq!(
        file_read_many_missing
            .payload
            .pointer("/routing/follow_up_requires_user_text_input")
            .and_then(Value::as_bool),
        Some(true)
    );
    assert_eq!(
        file_read_many_missing
            .payload
            .pointer("/routing/reason")
            .and_then(Value::as_str),
        Some("invalid_or_unreachable_paths")
    );
    assert_eq!(
        file_read_many_missing
            .payload
            .pointer("/routing/retryable")
            .and_then(Value::as_bool),
        Some(true)
    );
    assert_eq!(
        file_read_many_missing
            .payload
            .pointer("/routing/severity")
            .and_then(Value::as_str),
        Some("error")
    );
    assert_eq!(
        file_read_many_missing
            .payload
            .pointer("/recovery/action")
            .and_then(Value::as_str),
        Some("repair_paths_or_export_folder")
    );
    assert_eq!(
        file_read_many_missing
            .payload
            .pointer("/recovery/retryable")
            .and_then(Value::as_bool),
        Some(true)
    );
    assert_eq!(
        file_read_many_missing
            .payload
            .pointer("/recovery/class")
            .and_then(Value::as_str),
        Some("path_repair")
    );
    assert_eq!(
        file_read_many_missing
            .payload
            .pointer("/recovery/next_command")
            .and_then(Value::as_str),
        Some("folder_export")
    );
    assert_eq!(
        file_read_many_missing
            .payload
            .pointer("/recovery/requires_user_input")
            .and_then(Value::as_bool),
        Some(true)
    );

    let file_read_many_empty = handle(
        root.path(),
        "POST",
        &format!("/api/agents/{agent_id}/file/read-many"),
        br#"{}"#,
        &json!({"ok": true}),
    )
    .expect("file read many empty");
    assert_follow_up_requires_operator_input_contract(&file_read_many_empty.payload);
    assert_eq!(file_read_many_empty.status, 400);
    assert_eq!(
        file_read_many_empty
            .payload
            .pointer("/routing/hint")
            .and_then(Value::as_str),
        Some("paths_required")
    );
    assert_eq!(
        file_read_many_empty
            .payload
            .pointer("/routing/class")
            .and_then(Value::as_str),
        Some("path_repair")
    );
    assert_eq!(
        file_read_many_empty
            .payload
            .pointer("/routing/requires_binary_opt_in")
            .and_then(Value::as_bool),
        Some(false)
    );
    assert_eq!(
        file_read_many_empty
            .payload
            .pointer("/routing/requires_path_repair")
            .and_then(Value::as_bool),
        Some(true)
    );
    assert_eq!(
        file_read_many_empty
            .payload
            .pointer("/routing/requires_content_expansion")
            .and_then(Value::as_bool),
        Some(false)
    );
    assert_eq!(
        file_read_many_empty
            .payload
            .pointer("/routing/requires_mixed_follow_up")
            .and_then(Value::as_bool),
        Some(false)
    );
    assert_eq!(
        file_read_many_empty
            .payload
            .pointer("/routing/requires_partial_replay")
            .and_then(Value::as_bool),
        Some(false)
    );
    assert_eq!(
        file_read_many_empty
            .payload
            .pointer("/routing/blocker")
            .and_then(Value::as_str),
        Some("path_repair")
    );
    assert_eq!(
        file_read_many_empty
            .payload
            .pointer("/routing/binary_opt_in_blocked_count")
            .and_then(Value::as_u64),
        Some(0)
    );
    assert_eq!(
        file_read_many_empty
            .payload
            .pointer("/routing/requires_policy_repair")
            .and_then(Value::as_bool),
        Some(false)
    );
    assert_eq!(
        file_read_many_empty
            .payload
            .pointer("/routing/requires_follow_up")
            .and_then(Value::as_bool),
        Some(true)
    );
    assert_eq!(
        file_read_many_empty
            .payload
            .pointer("/routing/follow_up_can_auto_retry")
            .and_then(Value::as_bool),
        Some(false)
    );
    assert_eq!(
        file_read_many_empty
            .payload
            .pointer("/routing/follow_up_mode")
            .and_then(Value::as_str),
        Some("user_input")
    );
    assert_eq!(
        file_read_many_empty
            .payload
            .pointer("/routing/follow_up_task")
            .and_then(Value::as_str),
        Some("path_repair")
    );
    assert_eq!(
        file_read_many_empty
            .payload
            .pointer("/routing/follow_up_priority")
            .and_then(Value::as_str),
        Some("high")
    );
    assert_eq!(
        file_read_many_empty
            .payload
            .pointer("/routing/follow_up_blocking")
            .and_then(Value::as_bool),
        Some(true)
    );
    assert_eq!(
        file_read_many_empty
            .payload
            .pointer("/routing/follow_up_bucket")
            .and_then(Value::as_str),
        Some("blocking")
    );
    assert_eq!(
        file_read_many_empty
            .payload
            .pointer("/routing/follow_up_sla_seconds")
            .and_then(Value::as_u64),
        Some(30)
    );
    assert_eq!(
        file_read_many_empty
            .payload
            .pointer("/routing/follow_up_requires_immediate_action")
            .and_then(Value::as_bool),
        Some(true)
    );
    assert_eq!(
        file_read_many_empty
            .payload
            .pointer("/routing/follow_up_owner")
            .and_then(Value::as_str),
        Some("operator")
    );
    assert_eq!(
        file_read_many_empty
            .payload
            .pointer("/routing/follow_up_requires_confirmation")
            .and_then(Value::as_bool),
        Some(true)
    );
    assert_eq!(
        file_read_many_empty
            .payload
            .pointer("/routing/follow_up_action_kind")
            .and_then(Value::as_str),
        Some("repair")
    );
    assert_eq!(
        file_read_many_empty
            .payload
            .pointer("/routing/follow_up_requires_path_input")
            .and_then(Value::as_bool),
        Some(true)
    );
    assert_eq!(
        file_read_many_empty
            .payload
            .pointer("/routing/follow_up_can_defer")
            .and_then(Value::as_bool),
        Some(false)
    );
    assert_eq!(
        file_read_many_empty
            .payload
            .pointer("/routing/follow_up_requires_binary_opt_in_input")
            .and_then(Value::as_bool),
        Some(false)
    );
    assert_eq!(
        file_read_many_empty
            .payload
            .pointer("/routing/follow_up_requires_policy_repair_input")
            .and_then(Value::as_bool),
        Some(false)
    );
    assert_eq!(
        file_read_many_empty
            .payload
            .pointer("/routing/follow_up_requires_content_expansion_input")
            .and_then(Value::as_bool),
        Some(false)
    );
    assert_eq!(
        file_read_many_empty
            .payload
            .pointer("/routing/follow_up_requires_mixed_follow_up_input")
            .and_then(Value::as_bool),
        Some(false)
    );
    assert_eq!(
        file_read_many_empty
            .payload
            .pointer("/routing/follow_up_requires_partial_replay_input")
            .and_then(Value::as_bool),
        Some(false)
    );
    assert_eq!(
        file_read_many_empty
            .payload
            .pointer("/routing/follow_up_requires_user_text_input")
            .and_then(Value::as_bool),
        Some(true)
    );
    assert_eq!(
        file_read_many_empty
            .payload
            .pointer("/routing/reason")
            .and_then(Value::as_str),
        Some("paths_missing")
    );
    assert_eq!(
        file_read_many_empty
            .payload
            .pointer("/routing/retryable")
            .and_then(Value::as_bool),
        Some(true)
    );
    assert_eq!(
        file_read_many_empty
            .payload
            .pointer("/routing/severity")
            .and_then(Value::as_str),
        Some("error")
    );
    assert_eq!(
        file_read_many_empty
            .payload
            .pointer("/routing/contract_version")
            .and_then(Value::as_str),
        Some("v1")
    );
    assert_eq!(
        file_read_many_empty
            .payload
            .pointer("/recovery/action")
            .and_then(Value::as_str),
        Some("provide_paths_array")
    );
    assert_eq!(
        file_read_many_empty
            .payload
            .pointer("/recovery/retryable")
            .and_then(Value::as_bool),
        Some(true)
    );
    assert_eq!(
        file_read_many_empty
            .payload
            .pointer("/recovery/class")
            .and_then(Value::as_str),
        Some("input_repair")
    );
    assert_eq!(
        file_read_many_empty
            .payload
            .pointer("/recovery/next_command")
            .and_then(Value::as_str),
        Some("file_read_many")
    );
    assert_eq!(
        file_read_many_empty
            .payload
            .pointer("/recovery/requires_user_input")
            .and_then(Value::as_bool),
        Some(true)
    );

    let file_read_many_outside = handle(
        root.path(),
        "POST",
        &format!("/api/agents/{agent_id}/file/read-many"),
        br#"{"paths":["../outside.txt"]}"#,
        &json!({"ok": true}),
    )
    .expect("file read many outside");
    assert_follow_up_requires_operator_input_contract(&file_read_many_outside.payload);
    assert_eq!(file_read_many_outside.status, 400);
    assert_eq!(
        file_read_many_outside
            .payload
            .pointer("/routing/hint")
            .and_then(Value::as_str),
        Some("path_repair_required")
    );
    assert_eq!(
        file_read_many_outside
            .payload
            .pointer("/routing/class")
            .and_then(Value::as_str),
        Some("path_repair")
    );
    assert_eq!(
        file_read_many_outside
            .payload
            .pointer("/routing/requires_binary_opt_in")
            .and_then(Value::as_bool),
        Some(false)
    );
    assert_eq!(
        file_read_many_outside
            .payload
            .pointer("/routing/requires_path_repair")
            .and_then(Value::as_bool),
        Some(true)
    );
    assert_eq!(
        file_read_many_outside
            .payload
            .pointer("/routing/requires_content_expansion")
            .and_then(Value::as_bool),
        Some(false)
    );
    assert_eq!(
        file_read_many_outside
            .payload
            .pointer("/routing/requires_mixed_follow_up")
            .and_then(Value::as_bool),
        Some(false)
    );
    assert_eq!(
        file_read_many_outside
            .payload
            .pointer("/routing/requires_partial_replay")
            .and_then(Value::as_bool),
        Some(false)
    );
    assert_eq!(
        file_read_many_outside
            .payload
            .pointer("/routing/blocker")
            .and_then(Value::as_str),
        Some("path_repair")
    );
    assert_eq!(
        file_read_many_outside
            .payload
            .pointer("/routing/binary_opt_in_blocked_count")
            .and_then(Value::as_u64),
        Some(0)
    );
    assert_eq!(
        file_read_many_outside
            .payload
            .pointer("/routing/requires_policy_repair")
            .and_then(Value::as_bool),
        Some(false)
    );
    assert_eq!(
        file_read_many_outside
            .payload
            .pointer("/routing/requires_follow_up")
            .and_then(Value::as_bool),
        Some(true)
    );
    assert_eq!(
        file_read_many_outside
            .payload
            .pointer("/routing/follow_up_can_auto_retry")
            .and_then(Value::as_bool),
        Some(false)
    );
    assert_eq!(
        file_read_many_outside
            .payload
            .pointer("/routing/follow_up_mode")
            .and_then(Value::as_str),
        Some("user_input")
    );
    assert_eq!(
        file_read_many_outside
            .payload
            .pointer("/routing/follow_up_task")
            .and_then(Value::as_str),
        Some("path_repair")
    );
    assert_eq!(
        file_read_many_outside
            .payload
            .pointer("/routing/follow_up_priority")
            .and_then(Value::as_str),
        Some("high")
    );
    assert_eq!(
        file_read_many_outside
            .payload
            .pointer("/routing/follow_up_blocking")
            .and_then(Value::as_bool),
        Some(true)
    );
    assert_eq!(
        file_read_many_outside
            .payload
            .pointer("/routing/follow_up_bucket")
            .and_then(Value::as_str),
        Some("blocking")
    );
    assert_eq!(
        file_read_many_outside
            .payload
            .pointer("/routing/follow_up_sla_seconds")
            .and_then(Value::as_u64),
        Some(30)
    );
    assert_eq!(
        file_read_many_outside
            .payload
            .pointer("/routing/follow_up_requires_immediate_action")
            .and_then(Value::as_bool),
        Some(true)
    );
    assert_eq!(
        file_read_many_outside
            .payload
            .pointer("/routing/follow_up_owner")
            .and_then(Value::as_str),
        Some("operator")
    );
    assert_eq!(
        file_read_many_outside
            .payload
            .pointer("/routing/follow_up_requires_confirmation")
            .and_then(Value::as_bool),
        Some(true)
    );
    assert_eq!(
        file_read_many_outside
            .payload
            .pointer("/routing/follow_up_action_kind")
            .and_then(Value::as_str),
        Some("repair")
    );
    assert_eq!(
        file_read_many_outside
            .payload
            .pointer("/routing/follow_up_requires_path_input")
            .and_then(Value::as_bool),
        Some(true)
    );
    assert_eq!(
        file_read_many_outside
            .payload
            .pointer("/routing/follow_up_can_defer")
            .and_then(Value::as_bool),
        Some(false)
    );
    assert_eq!(
        file_read_many_outside
            .payload
            .pointer("/routing/follow_up_requires_binary_opt_in_input")
            .and_then(Value::as_bool),
        Some(false)
    );
    assert_eq!(
        file_read_many_outside
            .payload
            .pointer("/routing/follow_up_requires_policy_repair_input")
            .and_then(Value::as_bool),
        Some(false)
    );
    assert_eq!(
        file_read_many_outside
            .payload
            .pointer("/routing/follow_up_requires_content_expansion_input")
            .and_then(Value::as_bool),
        Some(false)
    );
    assert_eq!(
        file_read_many_outside
            .payload
            .pointer("/routing/follow_up_requires_mixed_follow_up_input")
            .and_then(Value::as_bool),
        Some(false)
    );
    assert_eq!(
        file_read_many_outside
            .payload
            .pointer("/routing/follow_up_requires_partial_replay_input")
            .and_then(Value::as_bool),
        Some(false)
    );
    assert_eq!(
        file_read_many_outside
            .payload
            .pointer("/routing/follow_up_requires_user_text_input")
            .and_then(Value::as_bool),
        Some(true)
    );
    assert_eq!(
        file_read_many_outside
            .payload
            .pointer("/routing/reason")
            .and_then(Value::as_str),
        Some("invalid_or_unreachable_paths")
    );
    assert_eq!(
        file_read_many_outside
            .payload
            .pointer("/routing/retryable")
            .and_then(Value::as_bool),
        Some(true)
    );
    assert_eq!(
        file_read_many_outside
            .payload
            .pointer("/routing/severity")
            .and_then(Value::as_str),
        Some("error")
    );
    assert_eq!(
        file_read_many_outside
            .payload
            .pointer("/recovery/action")
            .and_then(Value::as_str),
        Some("repair_paths_or_export_folder")
    );
    assert_eq!(
        file_read_many_outside
            .payload
            .pointer("/recovery/retryable")
            .and_then(Value::as_bool),
        Some(true)
    );
    assert_eq!(
        file_read_many_outside
            .payload
            .pointer("/recovery/class")
            .and_then(Value::as_str),
        Some("path_repair")
    );
    assert_eq!(
        file_read_many_outside
            .payload
            .pointer("/recovery/next_command")
            .and_then(Value::as_str),
        Some("folder_export")
    );
    assert_eq!(
        file_read_many_outside
            .payload
            .pointer("/recovery/requires_user_input")
            .and_then(Value::as_bool),
        Some(true)
    );

    let folder_export = handle(
        root.path(),
        "POST",
        &format!("/api/agents/{agent_id}/folder/export"),
        br#"{"path":"notes"}"#,
        &json!({"ok": true}),
    )
    .expect("folder export");
    assert_eq!(folder_export.payload.pointer("/folder/ok").and_then(Value::as_bool), Some(true));
    assert!(folder_export
        .payload
        .pointer("/folder/tree")
        .and_then(Value::as_str)
        .unwrap_or("")
        .contains("plan.txt"));
    assert!(folder_export
        .payload
        .pointer("/folder/tree")
        .and_then(Value::as_str)
        .unwrap_or("")
        .contains("extra.txt"));

    let folder_export_limited = handle(
        root.path(),
        "POST",
        &format!("/api/agents/{agent_id}/folder/export"),
        br#"{"path":"notes","max_entries":1}"#,
        &json!({"ok": true}),
    )
    .expect("folder export limited");
    assert_eq!(folder_export_limited.payload.pointer("/folder/truncated").and_then(Value::as_bool), Some(true));

    let folder_export_full = handle(
        root.path(),
        "POST",
        &format!("/api/agents/{agent_id}/folder/export"),
        br#"{"path":"notes","max_entries":1,"full":true}"#,
        &json!({"ok": true}),
    )
    .expect("folder export full");
    assert_eq!(folder_export_full.payload.pointer("/folder/truncated").and_then(Value::as_bool), Some(false));
    assert!(folder_export_full
        .payload
        .pointer("/folder/tree")
        .and_then(Value::as_str)
        .unwrap_or("")
        .contains("extra.txt"));

    let terminal = handle(
        root.path(),
        "POST",
        &format!("/api/agents/{agent_id}/terminal"),
        br#"{"command":"printf 'ok'","cwd":"notes"}"#,
        &json!({"ok": true}),
    )
    .expect("terminal");
    assert_eq!(terminal.payload.get("ok").and_then(Value::as_bool), Some(true));
    assert_eq!(terminal.payload.get("stdout").and_then(Value::as_str), Some("ok"));

    let upload = handle_with_headers(
        root.path(),
        "POST",
        &format!("/api/agents/{agent_id}/upload"),
        b"voice",
        &[("X-Filename", "voice.webm"), ("Content-Type", "audio/webm")],
        &json!({"ok": true}),
    )
    .expect("upload");
    assert_eq!(upload.payload.get("ok").and_then(Value::as_bool), Some(true));
    assert!(!clean_text(
        upload
            .payload
            .get("file_id")
            .and_then(Value::as_str)
            .unwrap_or(""),
        180
    )
    .is_empty());
    assert_eq!(upload.payload.get("filename").and_then(Value::as_str), Some("voice.webm"));
}

#[test]
fn full_mode_overrides_file_and_folder_limits() {
    let root = tempfile::tempdir().expect("tempdir");
    let notes_dir = root.path().join("notes");
    let _ = fs::create_dir_all(notes_dir.join("sub"));
    let _ = fs::write(notes_dir.join("plan.txt"), "ship it");
    let _ = fs::write(notes_dir.join("sub").join("extra.txt"), "plus one");

    let created = handle(
        root.path(),
        "POST",
        "/api/agents",
        br#"{"name":"Ops","role":"operator"}"#,
        &json!({"ok": true}),
    )
    .expect("create agent");
    let agent_id = clean_text(
        created
            .payload
            .get("agent_id")
            .and_then(Value::as_str)
            .unwrap_or(""),
        180,
    );
    assert!(!agent_id.is_empty());

    let file_read_limited = handle(
        root.path(),
        "POST",
        &format!("/api/agents/{agent_id}/file/read"),
        br#"{"path":"notes/plan.txt","max_bytes":4}"#,
        &json!({"ok": true}),
    )
    .expect("file read limited");
    assert_follow_up_requires_operator_input_contract(&file_read_limited.payload);
    assert_eq!(file_read_limited.payload.pointer("/file/truncated").and_then(Value::as_bool), Some(true));

    let file_read_full = handle(
        root.path(),
        "POST",
        &format!("/api/agents/{agent_id}/file/read"),
        br#"{"path":"notes/plan.txt","max_bytes":4,"full":true}"#,
        &json!({"ok": true}),
    )
    .expect("file read full");
    assert_follow_up_requires_operator_input_contract(&file_read_full.payload);
    assert_eq!(file_read_full.payload.pointer("/file/truncated").and_then(Value::as_bool), Some(false));

    let folder_export_limited = handle(
        root.path(),
        "POST",
        &format!("/api/agents/{agent_id}/folder/export"),
        br#"{"path":"notes","max_entries":1}"#,
        &json!({"ok": true}),
    )
    .expect("folder export limited");
    assert_eq!(folder_export_limited.payload.pointer("/folder/truncated").and_then(Value::as_bool), Some(true));

    let folder_export_full = handle(
        root.path(),
        "POST",
        &format!("/api/agents/{agent_id}/folder/export"),
        br#"{"path":"notes","max_entries":1,"full":true}"#,
        &json!({"ok": true}),
    )
    .expect("folder export full");
    assert_eq!(folder_export_full.payload.pointer("/folder/truncated").and_then(Value::as_bool), Some(false));
}
