fn family_contract_requirements(family: &str) -> FamilyContractRequirements {
    match family {
        "audit_self_healing_stack" => FamilyContractRequirements {
            required_true: &[
                "drift_detection_enabled",
                "self_healing_playbooks_enabled",
                "confidence_scoring_enabled",
                "cross_agent_verification_enabled",
                "human_review_gate_enforced",
                "conduit_only_enforced",
            ],
            min_values: &[
                ("confidence_high_threshold", 0.85),
                ("verification_agents", 2.0),
            ],
            max_values: &[("poll_interval_minutes", 15.0)],
        },
        "ultimate_evolution" => FamilyContractRequirements {
            required_true: &[
                "replication_policy_gate",
                "self_awareness_journal",
                "exotic_hardware_abstraction",
                "tokenomics_ledger_enforced",
                "symbiosis_interface",
                "universal_adapter_skeleton_key",
            ],
            min_values: &[("universal_adapter_coverage_pct", 80.0)],
            max_values: EMPTY_NUM_GATES,
        },
        "automation_mission_stack" => FamilyContractRequirements {
            required_true: &[
                "cron_scheduler_enabled",
                "multi_agent_handoff_enabled",
                "persistent_memory_enabled",
                "security_hardening_enabled",
                "mission_dashboard_enabled",
            ],
            min_values: EMPTY_NUM_GATES,
            max_values: &[
                ("checkpoint_interval_items", 10.0),
                ("checkpoint_interval_minutes", 2.0),
            ],
        },
        "duality_resilience_stack" => FamilyContractRequirements {
            required_true: &[
                "duality_bundle_emitted",
                "toll_prediction_enabled",
                "macro_composition_enabled",
                "dual_memory_tagging_enabled",
                "inversion_candidate_tagging_enabled",
            ],
            min_values: &[("harmony_score", 0.5), ("fractal_balance_score", 0.5)],
            max_values: &[("harmony_score", 1.0), ("fractal_balance_score", 1.0)],
        },
        "autonomy_opportunity_engine" => FamilyContractRequirements {
            required_true: &[
                "opportunity_discovery_engine",
                "inefficiency_scanner",
                "monetization_evaluator",
                "hindsight_ranking_engine",
            ],
            min_values: &[("creative_mode_signal_floor", 0.5)],
            max_values: EMPTY_NUM_GATES,
        },
        "cli_surface_hardening" => FamilyContractRequirements {
            required_true: &[
                "single_static_rust_binary",
                "rust_state_machine_core",
                "ts_cli_opt_in_extension",
                "thin_shim_wrapper",
                "node_absence_doctor_message",
            ],
            min_values: EMPTY_NUM_GATES,
            max_values: &[("static_binary_mb", 6.0)],
        },
        "client_model_access" => FamilyContractRequirements {
            required_true: &[
                "vibe_proxy_layer_enabled",
                "model_access_store_encrypted",
                "model_access_store_policy_gate",
            ],
            min_values: EMPTY_NUM_GATES,
            max_values: EMPTY_NUM_GATES,
        },
        "competitive_execution_moat" => FamilyContractRequirements {
            required_true: &[
                "aot_musl_zerocopy_lanes",
                "signed_receipt_export_sub_ms",
                "non_divergence_pre_execution_gate",
                "autonomous_swarm_workflow_evolution",
                "kernel_native_observability_governance",
                "edge_to_cloud_uniform_plan",
                "production_resilience_flywheel",
            ],
            min_values: &[("throughput_ops_sec", 11000.0)],
            max_values: &[("p95_ms", 50.0)],
        },
        "eyes_media_assimilation" => FamilyContractRequirements {
            required_true: &[
                "video_transcription_enabled",
                "course_assimilation_pipeline",
                "podcast_generator_enabled",
                "swarm_opportunity_integration",
            ],
            min_values: &[("transcript_quality_floor", 0.7)],
            max_values: EMPTY_NUM_GATES,
        },
        "eyes_computer_use" => FamilyContractRequirements {
            required_true: &[
                "parchi_computer_use_engine",
                "frontend_navigation_reliability",
                "computer_use_safety_gate",
                "superwhisper_voice_engine",
                "voice_session_blob_archival",
            ],
            min_values: &[("interaction_success_floor", 0.75)],
            max_values: EMPTY_NUM_GATES,
        },
        "eyes_lightpanda_router" => FamilyContractRequirements {
            required_true: &[
                "lightpanda_backend_enabled",
                "ultra_speed_profile_enabled",
                "seamless_multi_backend_router",
                "browser_session_blob_archival",
            ],
            min_values: &[("target_speedup_x", 10.0)],
            max_values: EMPTY_NUM_GATES,
        },
        "learning_rsi_pipeline" => FamilyContractRequirements {
            required_true: &[
                "signal_extraction_prm_judge",
                "hindsight_on_policy_distillation",
                "async_four_loop_training",
                "interaction_trajectory_blob_integration",
                "distributed_gym_factory",
                "adversarial_verification_pipeline",
                "training_flywheel_export",
                "real_world_product_verifier",
                "local_overnight_self_improvement",
                "real_usage_feedback_reinforcement",
                "single_directive_rl_engine",
                "emergent_strategy_discovery",
                "weekly_policy_retraining",
                "auto_rollback_enabled",
                "low_cost_overnight_loop",
            ],
            min_values: &[("training_loops_per_day", 1.0)],
            max_values: EMPTY_NUM_GATES,
        },
        "memory_depth_stack" => FamilyContractRequirements {
            required_true: &[
                "hierarchical_tree_index_builder",
                "agentic_tree_reasoning_retriever",
                "vision_page_retrieval",
                "tree_index_trace_blob_archival",
                "lossless_folder_backend",
                "automatic_sync_perfect_recall",
                "blob_lossless_hybrid_mirroring",
                "tinymax_lossless_mode",
                "tree_sitter_ast_indexer",
                "blast_radius_analyzer",
                "auto_codebase_wiki_generator",
                "mcp_graph_integration",
                "persistent_case_facts_scratchpad",
                "claim_source_provenance_mapping",
            ],
            min_values: EMPTY_NUM_GATES,
            max_values: &[("recall_budget_ms", 500.0)],
        },
        "organism_parallel_intelligence" => FamilyContractRequirements {
            required_true: &[
                "side_chat_forking_engine",
                "non_capturing_overlay_renderer",
                "file_overlap_peek_safety",
                "persistent_side_session_blob_integration",
                "hub_spoke_coordinator",
                "plan_vs_explore_subagent_separation",
                "autonomous_model_generator",
                "self_critique_alternative_perspectives",
                "explainer_slide_visual_synthesis",
                "model_evolution_archive",
            ],
            min_values: EMPTY_NUM_GATES,
            max_values: EMPTY_NUM_GATES,
        },
        "persona_enterprise_pack" => FamilyContractRequirements {
            required_true: &[
                "ai_ceo_persona_core",
                "departmental_agent_pack",
                "cross_agent_memory_sync",
                "role_based_agent_addition",
            ],
            min_values: EMPTY_NUM_GATES,
            max_values: EMPTY_NUM_GATES,
        },
        "safety_error_taxonomy" => FamilyContractRequirements {
            required_true: &["structured_error_taxonomy", "error_fail_closed_mapping"],
            min_values: EMPTY_NUM_GATES,
            max_values: EMPTY_NUM_GATES,
        },
        "security_sandbox_redteam" => FamilyContractRequirements {
            required_true: &[
                "wasm_capability_sandbox",
                "credential_injection_isolation",
                "verifiable_privacy_plane",
                "long_horizon_attack_chain_simulation",
                "zero_to_full_context_accumulation",
                "attack_trajectory_blob_archival",
            ],
            min_values: EMPTY_NUM_GATES,
            max_values: &[("max_escape_rate", 0.001)],
        },
        "skills_runtime_pack" => FamilyContractRequirements {
            required_true: &[
                "native_hf_cli_skill",
                "autonomous_model_dataset_pipeline",
                "hf_pure_context_mode",
                "hf_output_swarm_integration",
                "native_pomodoro_skill",
                "interactive_tui_focus_mode",
                "shell_composable_focus_status",
                "focus_session_blob_integration",
                "raspberry_pi_edge_template",
                "self_healing_server_agent",
                "orion_team_coordinator",
                "productivity_workflow_pack",
                "lens_scribe_code_agent_pack",
                "claude_style_prompt_chaining",
                "iterative_refinement_loop",
                "component_fullstack_scaffolding",
                "one_click_deployment_flow",
            ],
            min_values: EMPTY_NUM_GATES,
            max_values: EMPTY_NUM_GATES,
        },
        "swarm_runtime_scaling" => FamilyContractRequirements {
            required_true: &[
                "sentiment_swarm_core",
                "scenario_injection_live_consensus_mapper",
                "prediction_market_sentiment_oracle",
                "swarm_trajectory_storage_dream_refinement",
                "role_based_model_assignment",
                "automatic_parallel_exploration",
                "visual_subagent_dashboard",
                "subagent_edit_permission_gate",
                "planning_as_tool_engine",
                "filesystem_native_persistent_memory",
                "isolated_subagent_spawning",
                "shell_execution_safety_gates",
                "worker_heartbeat",
                "automatic_work_stealing",
                "supervisor_watchdog_respawn",
                "output_schema_enforcement",
                "frequent_checkpoint_recovery",
                "scope_boundary_validation",
                "realtime_aggregation_dashboard",
                "capability_advertisement_adaptive_partitioning",
                "cross_agent_dedup_reconciliation",
                "timeout_graceful_degradation",
            ],
            min_values: EMPTY_NUM_GATES,
            max_values: &[("max_timeout_seconds", 120.0)],
        },
        "client_wasm_bridge" => FamilyContractRequirements {
            required_true: &[
                "rust_wasm_bridge_engine",
                "browser_structured_concurrency",
                "standalone_html_demo_generator",
                "wasm_artifact_blob_archival",
            ],
            min_values: EMPTY_NUM_GATES,
            max_values: EMPTY_NUM_GATES,
        },
        "organism_adlc" => FamilyContractRequirements {
            required_true: &[
                "adlc_core_engine",
                "evolving_goals_replanning",
                "parallel_subagent_coordination",
                "continuous_testing_live_feedback",
            ],
            min_values: EMPTY_NUM_GATES,
            max_values: EMPTY_NUM_GATES,
        },
        "tinymax_extreme_profile" => FamilyContractRequirements {
            required_true: &[
                "trait_driven_swappable_tinymax_core",
                "sub5mb_idle_memory_mode",
            ],
            min_values: EMPTY_NUM_GATES,
            max_values: &[("idle_memory_mb", 5.0)],
        },
        "execution_streaming_stack" => FamilyContractRequirements {
            required_true: &[
                "ssd_streaming_enabled",
                "quantization_bridge_enabled",
                "os_page_cache_first",
                "kernel_bridge_enabled",
            ],
            min_values: &[("target_tokens_per_sec", 64.0)],
            max_values: &[("resident_memory_gb", 24.0)],
        },
        "execution_worktree_stack" => FamilyContractRequirements {
            required_true: &[
                "worktree_manager_enabled",
                "branch_isolation_enforced",
                "swarm_worktree_dispatch_enabled",
                "cleanup_enabled",
            ],
            min_values: &[("cleanup_interval_seconds", 30.0)],
            max_values: &[("max_residual_worktrees", 5.0)],
        },
        "assimilate_fast_stack" => FamilyContractRequirements {
            required_true: &[
                "fast_mode_enabled",
                "skeleton_cache_enabled",
                "progress_receipts_enabled",
                "parallel_microtasks_enabled",
                "warmup_enabled",
                "safety_guard_enabled",
            ],
            min_values: &[("target_latency_ms", 1.0)],
            max_values: &[("target_latency_ms", 60000.0)],
        },
        "workflow_open_swe_stack" => FamilyContractRequirements {
            required_true: &[
                "loop_registry_enabled",
                "git_bridge_enabled",
                "approval_middleware_enabled",
                "eval_harness_enabled",
                "memory_continuity_enabled",
            ],
            min_values: &[("eval_pass_floor", 0.5)],
            max_values: EMPTY_NUM_GATES,
        },
        "memory_context_maintenance" => FamilyContractRequirements {
            required_true: &[
                "staleness_tracking_enabled",
                "pre_generation_pruning_enabled",
                "emergency_compact_enabled",
                "context_observability_enabled",
                "safe_config_validation_enabled",
            ],
            min_values: &[("context_budget_tokens", 1024.0)],
            max_values: &[("context_budget_tokens", 10000000.0)],
        },
        "integration_lakehouse_stack" => FamilyContractRequirements {
            required_true: &[
                "unity_catalog_bridge_enabled",
                "mosaic_mapping_enabled",
                "mlflow_provider_enabled",
                "vector_automl_bridge_enabled",
                "dbrx_provider_enabled",
                "drift_monitoring_enabled",
            ],
            min_values: EMPTY_NUM_GATES,
            max_values: EMPTY_NUM_GATES,
        },
        "inference_adaptive_routing" => FamilyContractRequirements {
            required_true: &[
                "live_scoring_enabled",
                "rule_routing_enabled",
                "ordered_failover_enabled",
                "provider_observability_enabled",
            ],
            min_values: &[("min_success_rate", 0.5)],
            max_values: &[("max_latency_ms", 5000.0)],
        },
        "runtime_cleanup_autonomous" => FamilyContractRequirements {
            required_true: &[
                "eviction_matrix_enabled",
                "multi_trigger_scheduler_enabled",
                "tiered_pressure_enabled",
                "device_profiles_enabled",
                "protected_state_invariants_enabled",
                "audit_controls_enabled",
                "boundedness_gate_enabled",
            ],
            min_values: &[("cleanup_interval_minutes", 1.0)],
            max_values: &[("cleanup_interval_minutes", 60.0)],
        },
        "erp_agentic_stack" => FamilyContractRequirements {
            required_true: &[
                "erp_template_registry_enabled",
                "closed_loop_enabled",
                "lineage_gate_enabled",
            ],
            min_values: &[("max_loop_latency_ms", 1.0)],
            max_values: &[("max_loop_latency_ms", 60000.0)],
        },
        "tooling_uv_ruff_stack" => FamilyContractRequirements {
            required_true: &[
                "uv_bridge_enabled",
                "ruff_bridge_enabled",
                "isolated_env_enabled",
                "autowire_pipeline_enabled",
                "tooling_gate_enabled",
            ],
            min_values: &[("max_resolution_time_seconds", 1.0)],
            max_values: &[("max_resolution_time_seconds", 3600.0)],
        },
        "workflow_visual_bridge_stack" => FamilyContractRequirements {
            required_true: &[
                "canvas_bridge_enabled",
                "prompt_chain_enabled",
                "rag_integration_enabled",
                "tool_eval_enabled",
                "enterprise_observability_enabled",
            ],
            min_values: &[("cold_start_guard_ms", 1.0)],
            max_values: &[("cold_start_guard_ms", 120000.0)],
        },
        "infring_assimilation_stack" => FamilyContractRequirements {
            required_true: &[
                "provider_agnostic_driver_enabled",
                "context_budget_compaction_enabled",
                "websocket_streaming_enabled",
                "taint_tracking_enabled",
                "merkle_audit_chain_enabled",
                "manifest_signing_enabled",
                "ssrf_deny_paths_enabled",
                "hands_registry_enabled",
                "skills_promotion_pipeline_enabled",
                "hands_fail_closed_enabled",
            ],
            min_values: &[
                ("llm_driver_registry_count", 1.0),
                ("http_api_endpoints_count", 1.0),
            ],
            max_values: EMPTY_NUM_GATES,
        },
        "infring_detachment_stack" => FamilyContractRequirements {
            required_true: &[
                "source_assimilation_enabled",
                "nursery_migration_enabled",
                "external_dependency_detached",
                "operator_state_capture_enabled",
                "local_runtime_paths_enforced",
                "source_controlled_mirror_enabled",
                "llm_runtime_registry_enabled",
            ],
            min_values: &[
                ("source_files_required_min", 1.0),
                ("llm_registry_models_min", 1.0),
            ],
            max_values: &[("max_assimilation_copy_mb", 1024.0)],
        },
        _ => FamilyContractRequirements {
            required_true: EMPTY_REQUIRED_TRUE,
            min_values: EMPTY_NUM_GATES,
            max_values: EMPTY_NUM_GATES,
        },
    }
}
