// Layer ownership: client/runtime/systems/ui (dashboard chat UX surface only; no runtime authority).
function infringChatCatalogInitialState() {
  return {
    showAgentDrawer: false,
    agentDrawerLoading: false,
    agentDrawer: null,
    drawerTab: 'info',
    drawerConfigForm: {},
    drawerConfigSaving: false,
    drawerModelSaving: false,
    drawerIdentitySaving: false,
    drawerSavePending: false,
    drawerEditingModel: false,
    drawerEditingProvider: false,
    drawerEditingFallback: false,
    drawerEditingName: false,
    drawerEditingEmoji: false,
    drawerEmojiPickerOpen: false,
    drawerEmojiSearch: '',
    drawerAvatarUrlPickerOpen: false,
    drawerAvatarUrlDraft: '',
    drawerAvatarUploading: false,
    drawerAvatarUploadError: '',
    drawerNewModelValue: '',
    drawerNewProviderValue: '',
    drawerNewFallbackValue: '',
    drawerEmojiCatalog: [
      { emoji: '🤖', name: 'robot' },
      { emoji: '🧠', name: 'brain' },
      { emoji: '🧑\u200d💻', name: 'developer' },
      { emoji: '🛠️', name: 'tools' },
      { emoji: '🔬', name: 'research' },
      { emoji: '🧪', name: 'experiment' },
      { emoji: '🛰️', name: 'signal' },
      { emoji: '📡', name: 'telemetry' },
      { emoji: '🚀', name: 'launch' },
      { emoji: '🧭', name: 'navigator' },
      { emoji: '🦾', name: 'strong arm' },
      { emoji: '🔐', name: 'security' },
      { emoji: '🛡️', name: 'shield' },
      { emoji: '📈', name: 'growth' },
      { emoji: '📊', name: 'analytics' },
      { emoji: '📝', name: 'writer' },
      { emoji: '🎯', name: 'target' },
      { emoji: '💡', name: 'idea' },
      { emoji: '🌐', name: 'network' },
      { emoji: '🧱', name: 'builder' },
      { emoji: '🧰', name: 'toolbox' },
      { emoji: '🦉', name: 'wise owl' },
      { emoji: '🔥', name: 'fire' }
    ],
    drawerArchetypeOptions: ['Assistant', 'Researcher', 'Coder', 'Writer', 'DevOps', 'Support', 'Analyst', 'Custom'],
    drawerVibeOptions: ['professional', 'friendly', 'technical', 'creative', 'concise', 'mentor'],
    chatArchetypeTemplates: [
      {
        name: 'General Assistant',
        category: 'General',
        description: 'Versatile helper for everyday tasks and recommendations.',
        provider: 'groq',
        model: 'llama-3.3-70b-versatile',
        profile: 'full',
        archetype: 'assistant',
        system_prompt: 'You are a helpful, friendly assistant. Provide clear, accurate, and concise responses. Ask clarifying questions when needed.'
      },
      {
        name: 'Code Helper',
        category: 'Development',
        description: 'Programming-focused agent for writing, reviewing, and debugging.',
        provider: 'groq',
        model: 'llama-3.3-70b-versatile',
        profile: 'coding',
        archetype: 'coder',
        system_prompt: 'You are an expert programmer. Help users write clean, efficient code. Explain your reasoning and follow best practices.'
      },
      {
        name: 'Researcher',
        category: 'Research',
        description: 'Analytical agent for complex topics and synthesis.',
        provider: 'groq',
        model: 'llama-3.3-70b-versatile',
        profile: 'research',
        archetype: 'researcher',
        system_prompt: 'You are a research analyst. Break down complex topics with clear structure and concise findings.'
      },
      {
        name: 'Writer',
        category: 'Writing',
        description: 'Creative drafting, editing, and tone adaptation.',
        provider: 'groq',
        model: 'llama-3.3-70b-versatile',
        profile: 'full',
        archetype: 'writer',
        system_prompt: 'You are a skilled writer and editor. Help users create polished content and offer constructive improvements.'
      },
      {
        name: 'Data Analyst',
        category: 'Development',
        description: 'Data analysis, SQL/Python queries, and interpretation.',
        provider: 'groq',
        model: 'llama-3.3-70b-versatile',
        profile: 'coding',
        archetype: 'analyst',
        system_prompt: 'You are a data analysis expert. Help with dataset analysis, SQL/Python queries, and actionable interpretation.'
      },
      {
        name: 'DevOps Engineer',
        category: 'Development',
        description: 'CI/CD, infra, containers, and deployment reliability.',
        provider: 'groq',
        model: 'llama-3.3-70b-versatile',
        profile: 'automation',
        archetype: 'devops',
        system_prompt: 'You are a DevOps engineer. Help with CI/CD pipelines, Docker, infrastructure, deployment, and reliability.'
      },
      {
        name: 'Customer Support',
        category: 'Business',
        description: 'Empathetic and professional issue resolution.',
        provider: 'groq',
        model: 'llama-3.3-70b-versatile',
        profile: 'messaging',
        archetype: 'support',
        system_prompt: 'You are a professional support agent. Be empathetic, concise, and solution-oriented.'
      },
      {
        name: 'Tutor',
        category: 'General',
        description: 'Step-by-step explanations adapted to learner level.',
        provider: 'groq',
        model: 'llama-3.3-70b-versatile',
        profile: 'full',
        archetype: 'assistant',
        system_prompt: 'You are a patient tutor. Explain step-by-step, check understanding, and adapt to learner pace.'
      },
      {
        name: 'API Designer',
        category: 'Development',
        description: 'REST design, schema consistency, and versioning.',
        provider: 'groq',
        model: 'llama-3.3-70b-versatile',
        profile: 'coding',
        archetype: 'coder',
        system_prompt: 'You are an API design expert. Design clean RESTful APIs with robust schemas, error handling, and versioning.'
      },
      {
        name: 'Meeting Notes',
        category: 'Business',
        description: 'Summaries with decisions and action items.',
        provider: 'groq',
        model: 'llama-3.3-70b-versatile',
        profile: 'minimal',
        archetype: 'analyst',
        system_prompt: 'You summarize meetings into key decisions, action items, highlights, and follow-up questions.'
      },
      {
        name: 'Other',
        category: 'General',
        description: 'Specify a special purpose.',
        provider: 'groq',
        model: 'llama-3.3-70b-versatile',
        profile: 'full',
        archetype: 'custom',
        system_prompt: '',
        is_other: true
      }
    ],
    freshInitPersonalityCards: [
      {
        id: 'none',
        name: 'None',
        description: 'Use role defaults.',
        system_suffix: '',
        vibe: '',
      },
      {
        id: 'strategist',
        name: 'Strategist',
        description: 'Plan-first, structured, high-leverage.',
        system_suffix: 'Personality directive: be strategic, structured, and ROI-first. Offer concise plans and tradeoffs before action.',
        vibe: 'strategic',
      },
      {
        id: 'operator',
        name: 'Operator',
        description: 'Execution-focused, decisive, practical.',
        system_suffix: 'Personality directive: prioritize practical execution, clear next steps, and finish-line ownership.',
        vibe: 'operator',
      },
      {
        id: 'teacher',
        name: 'Teacher',
        description: 'Clear explanations, coaching-oriented.',
        system_suffix: 'Personality directive: teach with short, clear explanations and check understanding when useful.',
        vibe: 'mentor',
      },
      {
        id: 'creative',
        name: 'Creative',
        description: 'Idea-rich, exploratory, inventive.',
        system_suffix: 'Personality directive: be inventive and exploratory while staying concrete and useful.',
        vibe: 'creative',
      },
      {
        id: 'skeptic',
        name: 'Skeptic',
        description: 'Challenge assumptions, find weak points.',
        system_suffix: 'Personality directive: challenge assumptions, identify risks early, and pressure-test plans.',
        vibe: 'analytical',
      }
    ],
    freshInitLifespanCards: [
      {
        id: 'permanent',
        name: 'Permanent',
        description: 'No auto-expiry. Stays active until manual archive/revoke.',
        termination_condition: 'manual',
        indefinite: true,
        expiry_seconds: null,
      },
      {
        id: 'task',
        name: 'Until task is finished',
        description: 'Ends only when task is marked complete.',
        termination_condition: 'task_complete',
        indefinite: true,
        expiry_seconds: null,
      },
      {
        id: '1h',
        name: '1 hour',
        description: 'Auto-expires in 1 hour.',
        termination_condition: 'task_or_timeout',
        indefinite: false,
        expiry_seconds: 60 * 60,
      },
      {
        id: '1d',
        name: '1 day',
        description: 'Auto-expires in 1 day.',
        termination_condition: 'task_or_timeout',
        indefinite: false,
        expiry_seconds: 24 * 60 * 60,
      },
      {
        id: '1w',
        name: '1 week',
        description: 'Auto-expires in 1 week.',
        termination_condition: 'task_or_timeout',
        indefinite: false,
        expiry_seconds: 7 * 24 * 60 * 60,
      },
      {
        id: '1m',
        name: '1 month',
        description: 'Auto-expires in 1 month.',
        termination_condition: 'task_or_timeout',
        indefinite: false,
        expiry_seconds: 30 * 24 * 60 * 60,
      }
    ],
    freshInitVibeCards: [
      {
        id: 'none',
        name: 'None',
        description: 'Use role defaults.',
        system_suffix: '',
      },
      {
        id: 'friendly',
        name: 'Friendly',
        description: 'Warm, approachable, and collaborative.',
        system_suffix: 'Vibe directive: keep the tone warm, approachable, and encouraging while staying concise.',
      },

      {
        id: 'direct',
        name: 'Direct',
        description: 'Straight to the point with minimal fluff.',
        system_suffix: 'Vibe directive: be direct and concise; prioritize concrete recommendations over exposition.',
      },
      {
        id: 'professional',
        name: 'Professional',
        description: 'Structured and businesslike.',
        system_suffix: 'Vibe directive: maintain a professional, structured tone suitable for business operations.',
      },
      {
        id: 'analytical',
        name: 'Analytical',
        description: 'Evidence-driven and detail-focused.',
        system_suffix: 'Vibe directive: reason from evidence, make assumptions explicit, and surface tradeoffs.',
      },
      {
        id: 'creative',
        name: 'Creative',
        description: 'Inventive and exploratory.',
        system_suffix: 'Vibe directive: propose inventive options and novel angles while staying practical.',
      }
    ],
    slashCommands: [
      { cmd: '/help', desc: 'Show available commands' },
      { cmd: '/agents', desc: 'Switch to Agents page' },
      { cmd: '/new', desc: 'Reset session (clear history)' },
      { cmd: '/compact', desc: 'Trigger LLM session compaction' },
      { cmd: '/model', desc: 'Show or switch model (/model [name])' },
      { cmd: '/apikey', desc: 'Add API key or local model path (/apikey [key|path])' },
      { cmd: '/file', desc: 'Render full file output in chat (/file [path])' },
      { cmd: '/folder', desc: 'Render folder tree + downloadable archive (/folder [path])' },
      { cmd: '/stop', desc: 'Cancel current agent run' },
      { cmd: '/usage', desc: 'Show session token usage & cost' },
      { cmd: '/think', desc: 'Toggle extended thinking (/think [on|off|stream])' },
      { cmd: '/context', desc: 'Show context window usage & pressure' },
      { cmd: '/verbose', desc: 'Cycle tool detail level (/verbose [off|on|full])' },
      { cmd: '/queue', desc: 'Check if agent is processing' },
      { cmd: '/status', desc: 'Show system status' },
      { cmd: '/alerts', desc: 'Show proactive telemetry alerts' },
      { cmd: '/next', desc: 'Show predicted next high-ROI actions' },
      { cmd: '/memory', desc: 'Show memory hygiene + cleanup recommendations' },
      { cmd: '/continuity', desc: 'Show pending actions across channels/sessions/tasks' },
      { cmd: '/aliases', desc: 'List active slash aliases' },
      { cmd: '/alias', desc: 'Create custom alias (/alias /short /target ...)' },
      { cmd: '/opt', desc: 'Suggest worker optimization / hibernation actions' },
      { cmd: '/clear', desc: 'Clear chat display' },
      { cmd: '/exit', desc: 'Disconnect from agent' },
      { cmd: '/budget', desc: 'Show spending limits and current costs' },
      { cmd: '/peers', desc: 'Show OFP peer network status' },
      { cmd: '/a2a', desc: 'List discovered external A2A agents' }
    ],
    tokenCount: 0,
    promptSuggestions: [],
    suggestionsLoading: false,
    promptSuggestionsEnabled: true,
    promptSuggestionsStorageKey: 'infring-chat-prompt-suggestions-enabled-v1',
    _suggestionFetchSeq: 0,
    _lastSuggestionsAt: 0,
    _lastSuggestionsAgentId: '',
    _pointerTrailLastAt: 0,
    _pointerTrailRaf: 0,
    _pointerTrailLastX: 0,
    _pointerTrailLastY: 0,
    _pointerTrailSeeded: false,
    _pointerTrailHeadLastAt: 0,
    _pointerOrbEl: null,
    _agentTrailRaf: 0,
    _agentTrailHost: null,
    _agentTrailState: null,
    _agentTrailLastAt: 0,
    _agentTrailLastDotAt: 0,
    _agentTrailSeeded: false,
    _agentTrailOrbEl: null,
    _agentTrailOrbElevated: false,
    _agentTrailTeleportTimer: 0,
    _agentTrailTeleportTargetX: NaN,
    _agentTrailTeleportTargetY: NaN,
    _agentTrailTeleportToggleIndex: true,
    _agentTrailListenTimer: 0,
    _agentTrailListening: false,
    chatResizeBlurActive: false,
    _chatResizeBlurTimer: 0,
    _chatResizeObserver: null,
    _chatResizeLastWidth: 0,
    _chatInputOverlayObserver: null,
    _chatInputOverlayResizeHandler: null,
    _progressCache: {},
    _freshInitThreadShownFor: '',
    _releaseCheckInFlight: false,
    _releaseUpdateNoticeKey: '',
    systemUpdateBusy: false
  };
}
