// Layer ownership: client/runtime/systems/ui (dashboard chat UX surface only; no runtime authority).
function infringChatCoreInitialState() {
  return {
    currentAgent: null,
    systemThreadId: 'system',
    systemThreadName: 'System',
    systemThreadEmoji: '\u2699\ufe0f',
    systemTerminalSessionId: '',
    messages: [],
    inputText: '',
    chatInputHistory: [],
    terminalInputHistory: [],
    chatInputHistoryCursor: -1,
    terminalInputHistoryCursor: -1,
    chatInputHistoryDraft: '',
    terminalInputHistoryDraft: '',
    inputHistoryMaxEntries: 500,
    inputHistoryCacheKey: 'infring-chat-input-history-v1',
    inputHistorySessionScopePrefix: 'session:',
    _inputHistoryByAgent: {},
    _inputHistoryApplying: false,
    sending: false,
    messageQueue: [],    // Queue for messages sent while streaming
    promptQueueDragId: '',
    _promptQueueSeq: 0,
    thinkingMode: 'off', // 'off' | 'on' | 'stream'
    _wsAgent: null,
    showAttachMenu: false,
    attachPickerSessionActive: false,
    attachPickerRestoreMode: 'send',
    _attachPickerFocusListener: null,
    _attachPickerFocusTimer: 0,
    showSlashMenu: false,
    slashFilter: '',
    slashIdx: 0,
    slashAliasMap: {},
    slashAliasStorageKey: 'infring-chat-slash-aliases-v1',
    attachments: [],
    pasteToMarkdownEnabled: true,
    pasteToMarkdownCharThreshold: 2000,
    pasteToMarkdownLineThreshold: 40,
    dragOver: false,
    contextPressure: 'low',
    contextWindow: 8192,
    contextApproxTokens: 0,
    terminalMode: false,
    terminalCwd: '/workspace',
    terminalShortcutHint: 'Ctrl+\\',
    terminalCursorFocused: false,
    terminalSelectionStart: 0,
    _contextTelemetryTimer: null,
    _telemetryAlertsTimer: null,
    _lastTelemetryAlertDigest: '',
    telemetryNextActions: [],
    _telemetrySnapshot: null,
    _lastContextRequestAt: 0,
    _contextWindowByModel: {},
    _contextModelsFetchedAt: 0,
    _typingTimeout: null,
    // Multi-session state
    sessions: [],
    sessionsOpen: false,
    searchOpen: false,
    searchQuery: '',
    messageDisplayInitialLimit: 10,
    messageDisplayStep: 5,
    messageDisplayCount: 10,
    messageTextRenderWindowRadius: 20,
    _messageDisplayKey: '',
    // Voice recording state
    recording: false,
    _mediaRecorder: null,
    _audioChunks: [],
    recordingTime: 0,
    _recordingTimer: null,
    // Model autocomplete state
    showModelPicker: false,
    modelPickerList: [],
    modelPickerFilter: '',
    modelPickerIdx: 0,
    // Model switcher dropdown
    showModelSwitcher: false,
    modelSwitcherFilter: '',
    modelSwitcherProviderFilter: '',
    modelSwitcherIdx: 0,
    showGitTreeMenu: false,
    gitTreeMenuLoading: false,
    gitTreeMenuError: '',
    gitTreeMenuItems: [],
    gitTreeSwitching: false,
    modelApiKeyInput: '',
    modelApiKeySaving: false,
    modelApiKeyStatus: '',
    modelDownloadBusy: {},
    modelDownloadProgress: {},
    _modelDownloadProgressTimers: {},
    modelSwitching: false,
    _modelCache: null,
    _modelCacheTime: 0,
    _modelLogoFailIndex: {},
    _modelSourceLogoFailIndex: {},
    _modelSwitcherViewCache: null,
    _chatMapWheelLockInstalled: false,
    sessionLoading: false,
    _sessionLoadSeq: 0,
    _hasMoreMessages: false,
    _messagePageOffset: 0,
    _olderMessagesLoading: false,
    toolPreviewMaxLines: 2,
    toolPreviewMaxChars: 100,
    messageHydration: {},
    messageHydrationReady: false,
    _forcedHydrateById: {},
    _renderWindowRaf: 0,
    showFreshArchetypeTiles: false,
    freshInitTemplateDef: null,
    freshInitTemplateName: '',
    freshInitName: '',
    freshInitEmoji: '',
    freshInitDefaultName: '',
    freshInitDefaultEmoji: '',
    freshInitLaunching: false,
    freshInitRevealMenu: false,
    freshInitStageToken: 0,
    freshInitAvatarUrl: '',
    freshInitAvatarUploading: false,
    freshInitAvatarUploadError: '',
    freshInitEmojiPickerOpen: false,
    freshInitEmojiSearch: '',
    freshInitOtherPrompt: '',
    freshInitAwaitingOtherPrompt: false,
    freshInitPersonalityId: 'none',
    freshInitLifespanId: '1h',
    freshInitAdvancedOpen: false,
    freshInitVibeId: 'none',
    freshInitModelSuggestions: [],
    freshInitModelSelection: '',
    freshInitModelManual: false,
    freshInitModelSuggestLoading: false,
    freshInitPermissionOverrides: {},
    freshInitPermissionCatalog: [
      { category: 'web', name: 'Web', permissions: [
        { key: 'web.search.basic', label: 'Basic web search', default_checked: true },
        { key: 'web.fetch.url', label: 'Fetch URL content', default_checked: false }
      ]},
      { category: 'agent', name: 'Agent', permissions: [
        { key: 'agent.spawn', label: 'Spawn child agents', default_checked: false },
        { key: 'agent.permissions.manage', label: 'Manage permissions', default_checked: false }
      ]},
      { category: 'file', name: 'File', permissions: [
        { key: 'file.read.workspace', label: 'Read workspace files', default_checked: false },
        { key: 'file.write.workspace', label: 'Write workspace files', default_checked: false },
        { key: 'file.delete.workspace', label: 'Delete workspace files', default_checked: false }
      ]},
      { category: 'github', name: 'GitHub', permissions: [
        { key: 'github.issue.create', label: 'Create GitHub issues', default_checked: false }
      ]},
      { category: 'terminal', name: 'Terminal', permissions: [
        { key: 'terminal.exec', label: 'Execute terminal commands', default_checked: false }
      ]},
      { category: 'memory', name: 'Memory', permissions: [
        { key: 'memory.write', label: 'Write durable memory', default_checked: false }
      ]}
    ],
    conversationCache: {},
    conversationCacheKey: 'of-chat-conversation-cache-v1',
    conversationCacheVersionKey: 'of-chat-conversation-cache-version',
    conversationCacheVersion: 'v2-source-runs-20260325',
    messageLineExpandState: {},
    messageLineExpandStep: 20,
    _persistTimer: null,
    _responseStartedAt: 0,
    typingWordCadenceMs: 1,
    _pointerGridHideTimer: null,
    _pointerTrailMouseHeld: false,
    _pointerTrailHoldHost: null,
    _pointerTrailMouseUpHandler: null,
    _pendingAutoModelSwitchBaseline: '',
    _pendingWsRequest: null,
    _pendingWsRecovering: false,
    _wsConnectSeq: 0,
    _inflightPayload: null,
    _inflightFailoverInProgress: false,
    _sendWatchdogTimer: null,
    _continuitySnapshot: null,
    _hoverClearTimer: 0,
    modelNoticeCache: {},
    modelNoticeCacheKey: 'of-chat-model-notices-v1',
    modelUsageCache: {},
    modelUsageCacheKey: 'of-chat-model-usage-v1',
    showScrollDown: false,
    scrollBottomBufferPx: 84,
    scrollBottomFollowTolerancePx: 32,
    scrollBottomClampSlackPx: 16,
    _stickToBottom: true,
    hoveredMessageDomId: '',
    directHoveredMessageDomId: '',
    selectedMessageDomId: '',
    _systemMessageDedupeIndex: {},
    mapStepIndex: -1,
    suppressMapPreview: false,
    _mapPreviewSuppressTimer: null,
    _scrollSyncFrame: 0,
    _bottomClampTimer: 0,
    _lastMessagesScrollAt: 0,
    _openPinToken: 0,
    _openPinRaf: 0,
    _openPinTimer: 0,
    _lastPointerClientX: 0,
    _lastPointerClientY: 0,
    _lastInactiveNoticeKey: '',
    _agentMissingSince: 0,
    _agentMissingAgentId: '',
    _agentMissingGraceMs: 12000,
    collapsedMessageDays: {}
  };
}
