
fn interoperability_command(parsed: &crate::ParsedArgs) -> Result<Value, String> {
    let op = clean(
        parsed
            .flags
            .get("op")
            .map(String::as_str)
            .unwrap_or("status"),
        16,
    )
    .to_ascii_lowercase();
    if op == "status" {
        return Ok(json!({
            "ok": true,
            "type": "government_plane_interoperability",
            "lane": LANE_ID,
            "ts": now_iso(),
            "op": op,
            "required_standards": ["PKI", "SAML", "OIDC", "SMIME", "IPv6", "DNSSEC", "OAuth2"],
            "claim_evidence": [{
                "id": "V7-GOV-001.8",
                "claim": "interoperability_profile_requires_standards_first_contracts",
                "evidence": {"required_count": 7}
            }]
        }));
    }
    if op != "validate" {
        return Err("interoperability_op_invalid".to_string());
    }
    let profile = parse_json_or_empty(parsed.flags.get("profile-json"));
    let standards = profile
        .get("standards")
        .and_then(Value::as_array)
        .cloned()
        .unwrap_or_default()
        .iter()
        .filter_map(Value::as_str)
        .map(|s| s.to_ascii_uppercase())
        .collect::<Vec<_>>();
    let required = ["PKI", "SAML", "OIDC", "SMIME", "IPV6", "DNSSEC", "OAUTH2"];
    let missing = required
        .iter()
        .filter(|req| !standards.iter().any(|s| s == **req))
        .map(|s| s.to_string())
        .collect::<Vec<_>>();
    let endpoint = profile
        .get("endpoint")
        .and_then(Value::as_str)
        .unwrap_or("");
    let disallow_plain_http = endpoint.starts_with("http://");
    let ok = missing.is_empty() && !disallow_plain_http;
    Ok(json!({
        "ok": ok,
        "type": "government_plane_interoperability",
        "lane": LANE_ID,
        "ts": now_iso(),
        "op": op,
        "missing_standards": missing,
        "endpoint": endpoint,
        "claim_evidence": [{
            "id": "V7-GOV-001.8",
            "claim": "interoperability_validator_rejects_non_standard_profiles_and_plain_http_downgrades",
            "evidence": {"ok": ok}
        }]
    }))
}

fn ato_pack_command(root: &Path, parsed: &crate::ParsedArgs) -> Result<Value, String> {
    let op = clean(
        parsed
            .flags
            .get("op")
            .map(String::as_str)
            .unwrap_or("status"),
        16,
    )
    .to_ascii_lowercase();
    let docs_dir = root.join("docs/government");
    let required = [
        "SYSTEM_SECURITY_PLAN.md",
        "CONTINGENCY_PLAN.md",
        "INCIDENT_RESPONSE_PLAN.md",
        "PRIVACY_IMPACT_ASSESSMENT.md",
        "CONFIGURATION_MANAGEMENT_PLAN.md",
        "TEST_PLAN_AND_RESULTS.md",
    ];
    if op == "generate" {
        fs::create_dir_all(&docs_dir).map_err(|e| format!("ato_docs_mkdir_failed:{e}"))?;
        for name in required {
            let path = docs_dir.join(name);
            if !path.exists() {
                let body = format!(
                    "# {name}\n\nGenerated by government-plane ATO pack.\n\n- Generated: {}\n- Scope: FedRAMP/CMMC/CC\n",
                    now_iso()
                );
                fs::write(&path, body)
                    .map_err(|e| format!("ato_doc_write_failed:{}:{e}", path.display()))?;
            }
        }
    } else if op != "status" {
        return Err("ato_pack_op_invalid".to_string());
    }
    let manifest = required
        .iter()
        .map(|name| {
            let p = docs_dir.join(name);
            json!({
                "path": p.to_string_lossy().to_string(),
                "exists": p.exists(),
                "sha256": if p.exists() { sha256_hex_str(&fs::read_to_string(&p).unwrap_or_default()) } else { String::new() }
            })
        })
        .collect::<Vec<_>>();
    let ok = manifest
        .iter()
        .all(|row| row.get("exists").and_then(Value::as_bool) == Some(true));
    Ok(json!({
        "ok": ok,
        "type": "government_plane_ato_pack",
        "lane": LANE_ID,
        "ts": now_iso(),
        "op": op,
        "manifest": manifest,
        "claim_evidence": [{
            "id": "V7-GOV-001.9",
            "claim": "ato_documentation_pack_materializes_required_security_and_operational_artifacts",
            "evidence": {"ok": ok}
        }]
    }))
}

pub fn run(root: &Path, argv: &[String]) -> i32 {
    let parsed = parse_args(argv);
    let command = parsed
        .positional
        .first()
        .map(|v| v.trim().to_ascii_lowercase())
        .unwrap_or_else(|| "status".to_string());
    if matches!(command.as_str(), "help" | "--help" | "-h") {
        usage();
        return 0;
    }
    let strict = parse_bool(parsed.flags.get("strict"), true);
    let bypass = conduit_bypass_requested(&parsed.flags);
    let conduit = build_conduit_enforcement(
        root,
        ENV_KEY,
        LANE_ID,
        strict,
        &command,
        "government_plane_conduit_enforcement",
        "client/protheusctl -> core/government-plane",
        bypass,
        vec![json!({
            "id": "V7-GOV-001.8",
            "claim": "government_plane_commands_are_conduit_routed_with_fail_closed_bypass_rejection",
            "evidence": {"command": command, "bypass_requested": bypass}
        })],
    );
    if strict && !conduit.get("ok").and_then(Value::as_bool).unwrap_or(false) {
        let payload = json!({
            "ok": false,
            "type": "government_plane",
            "lane": LANE_ID,
            "ts": now_iso(),
            "command": command,
            "error": "conduit_bypass_rejected"
        });
        return emit(root, &command, strict, payload, Some(&conduit));
    }
    let result = match command.as_str() {
        "attestation" => attestation_command(root, &parsed),
        "classification" => classification_command(root, &parsed),
        "nonrepudiation" => nonrepudiation_command(root, &parsed),
        "diode" => diode_command(root, &parsed),
        "soc" => soc_command(root, &parsed),
        "coop" => coop_command(root, &parsed),
        "proofs" => proofs_command(root, &parsed),
        "interoperability" => interoperability_command(&parsed),
        "ato-pack" | "ato_pack" => ato_pack_command(root, &parsed),
        "status" => Ok(json!({
            "ok": true,
            "type": "government_plane_status",
            "lane": LANE_ID,
            "ts": now_iso(),
            "state_root": lane_root(root).to_string_lossy().to_string(),
            "latest_path": latest_path(root, ENV_KEY, LANE_ID).to_string_lossy().to_string(),
            "history_path": history_path(root, ENV_KEY, LANE_ID).to_string_lossy().to_string()
        })),
        _ => Err("unknown_government_command".to_string()),
    };
    match result {
        Ok(payload) => emit(root, &command, strict, payload, Some(&conduit)),
        Err(error) => emit(
            root,
            &command,
            strict,
            json!({
                "ok": false,
                "type": "government_plane",
                "lane": LANE_ID,
                "ts": now_iso(),
                "command": command,
                "error": error
            }),
            Some(&conduit),
        ),
    }
}

