{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "infring.serviceAccountName" . }}
  labels:
    app.kubernetes.io/name: {{ include "infring.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  annotations:
{{- if .Values.serviceAccount.annotations }}
{{ toYaml .Values.serviceAccount.annotations | indent 4 }}
{{- else }}
    {}
{{- end }}
{{- end }}
