
fn strip_invisible_and_controls(raw: &str) -> String {
    raw.chars()
        .filter(|ch| {
            !matches!(
                *ch,
                '\u{200B}'
                    | '\u{200C}'
                    | '\u{200D}'
                    | '\u{2060}'
                    | '\u{FEFF}'
                    | '\u{202A}'
                    | '\u{202B}'
                    | '\u{202C}'
                    | '\u{202D}'
                    | '\u{202E}'
            ) && (!ch.is_control() || ch.is_ascii_whitespace())
        })
        .collect::<String>()
}

fn extract_tags_from_chunk(chunk: &str) -> Vec<String> {
    for line in chunk.lines() {
        let normalized = strip_invisible_and_controls(line);
        let trimmed = normalized.trim();
        if let Some(rest) = trimmed.strip_prefix("tags:") {
            let mut tags = parse_tags_line(rest);
            tags.sort();
            tags.dedup();
            return tags;
        }
    }
    vec![]
}

fn extract_summary_from_chunk(chunk: &str, node_id: &str) -> String {
    for line in chunk.lines() {
        let normalized = strip_invisible_and_controls(line);
        let trimmed = normalized.trim();
        if let Some(rest) = trimmed.strip_prefix("# ") {
            let summary = sanitize_table_cell(rest);
            if !summary.is_empty() {
                return summary;
            }
        }
    }
    sanitize_table_cell(node_id)
}

fn scan_daily_entries(root: &Path) -> (Vec<IndexEntry>, usize) {
    let memory_dir = root.join("memory");
    let Ok(entries) = fs::read_dir(&memory_dir) else {
        return (vec![], 0);
    };

    let mut files: Vec<String> = vec![];
    for entry in entries.flatten() {
        let file_name = entry.file_name().to_string_lossy().to_string();
        if !is_date_memory_file(&file_name) {
            continue;
        }
        files.push(file_name);
    }
    files.sort();

    let mut out: Vec<IndexEntry> = vec![];
    let mut seen: HashSet<String> = HashSet::new();
    let mut files_scanned = 0usize;
    for file_name in files {
        files_scanned += 1;
        let file_abs = memory_dir.join(&file_name);
        let Ok(content) = fs::read_to_string(&file_abs) else {
            continue;
        };
        let file_rel = format!("client/memory/{file_name}");
        for chunk in content.split("<!-- NODE -->") {
            let node_id = node_id_from_chunk(chunk);
            if node_id.is_empty() {
                continue;
            }
            let key = format!("{node_id}@{file_rel}");
            if seen.contains(&key) {
                continue;
            }
            seen.insert(key);
            out.push(IndexEntry {
                node_id: node_id.clone(),
                uid: extract_uid_from_chunk(chunk),
                file_rel: file_rel.clone(),
                summary: extract_summary_from_chunk(chunk, &node_id),
                tags: extract_tags_from_chunk(chunk),
            });
        }
    }

    out.sort_by(|a, b| {
        if a.file_rel != b.file_rel {
            return a.file_rel.cmp(&b.file_rel);
        }
        a.node_id.cmp(&b.node_id)
    });
    (out, files_scanned)
}

fn build_memory_index_doc(entries: &[IndexEntry]) -> String {
    let mut lines: Vec<String> = vec![
        "# MEMORY_INDEX.md".to_string(),
        "# Generated by infring-memory-core build-index".to_string(),
        "".to_string(),
        "| node_id | uid | tags | file | summary |".to_string(),
        "|---|---|---|---|---|".to_string(),
    ];

    if entries.is_empty() {
        lines.push("| | | | | |".to_string());
        return lines.join("\n");
    }

    for entry in entries {
        let tags = entry
            .tags
            .iter()
            .map(|tag| format!("#{tag}"))
            .collect::<Vec<String>>()
            .join(" ");
        lines.push(format!(
            "| `{}` | `{}` | {} | `{}` | {} |",
            sanitize_table_cell(&entry.node_id),
            sanitize_table_cell(&entry.uid),
            sanitize_table_cell(&tags),
            sanitize_table_cell(&entry.file_rel),
            sanitize_table_cell(&entry.summary)
        ));
    }
    lines.join("\n")
}

fn build_tags_index_doc(entries: &[IndexEntry]) -> (String, usize) {
    let mut tags: BTreeMap<String, BTreeSet<String>> = BTreeMap::new();
    for entry in entries {
        for tag in &entry.tags {
            if tag.is_empty() {
                continue;
            }
            tags.entry(tag.clone())
                .or_default()
                .insert(entry.node_id.clone());
        }
    }

    let mut lines: Vec<String> = vec![
        "# TAGS_INDEX.md".to_string(),
        "# Generated by infring-memory-core build-index".to_string(),
        "".to_string(),
    ];
    for (tag, node_ids) in &tags {
        lines.push(format!("## `{}`", sanitize_table_cell(tag)));
        for node_id in node_ids {
            lines.push(format!("- `{}`", sanitize_table_cell(node_id)));
        }
        lines.push(String::new());
    }
    (lines.join("\n"), tags.len())
}

fn sort_entries_for_get(entries: &mut [IndexEntry]) {
    entries.sort_by(|a, b| {
        let da = extract_date_from_path(&a.file_rel);
        let db = extract_date_from_path(&b.file_rel);
        if db != da {
            return db.cmp(&da);
        }
        let aa = if a.file_rel.contains("/_archive/") {
            1
        } else {
            0
        };
        let bb = if b.file_rel.contains("/_archive/") {
            1
        } else {
            0
        };
        if aa != bb {
            return aa.cmp(&bb);
        }
        let node_cmp = a.node_id.cmp(&b.node_id);
        if node_cmp != Ordering::Equal {
            return node_cmp;
        }
        a.file_rel.cmp(&b.file_rel)
    });
}

fn detect_default_root() -> PathBuf {
    let cwd = env::current_dir().unwrap_or_else(|_| PathBuf::from("."));
    cwd.join("../../..")
        .canonicalize()
        .unwrap_or_else(|_| cwd.clone())
}

fn run_probe(args: &HashMap<String, String>) {
    let root = PathBuf::from(arg_or_default(
        args,
        "root",
        detect_default_root().to_string_lossy().as_ref(),
    ));
    let started = Instant::now();
    let (_source, entries) = load_memory_index(&root);
    let elapsed_ms = started.elapsed().as_millis() as u64;
    let result = ProbeResult {
        ok: true,
        parity_error_count: 0,
        estimated_ms: elapsed_ms.max(1),
    };
    let _ = entries;
    let out = serde_json::to_string(&result).expect("serialize probe result");
    println!("{}", out);
}
