use serde::{Deserialize, Serialize};
use std::fs;
use std::io;
use std::path::{Path, PathBuf};

#[derive(Clone, Debug, Serialize, Deserialize)]
pub enum TemplateKind {
    SingleAgent,
    Swarm,
    Rag,
    Voice,
}

impl TemplateKind {
    pub fn parse(raw: &str) -> Option<Self> {
        match raw.trim().to_ascii_lowercase().as_str() {
            "single-agent" | "single" => Some(Self::SingleAgent),
            "swarm" => Some(Self::Swarm),
            "rag" => Some(Self::Rag),
            "voice" => Some(Self::Voice),
            _ => None,
        }
    }

    pub fn as_str(&self) -> &'static str {
        match self {
            Self::SingleAgent => "single-agent",
            Self::Swarm => "swarm",
            Self::Rag => "rag",
            Self::Voice => "voice",
        }
    }
}

#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct TemplateScaffoldOptions {
    pub name: String,
    pub out_dir: PathBuf,
    pub force: bool,
}

#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct TemplateScaffoldResult {
    pub template: String,
    pub root: String,
    pub created_files: Vec<String>,
}

pub fn scaffold_template(
    kind: TemplateKind,
    options: &TemplateScaffoldOptions,
) -> io::Result<TemplateScaffoldResult> {
    let root = options.out_dir.join(options.name.as_str());
    if root.exists() && !options.force {
        return Err(io::Error::new(
            io::ErrorKind::AlreadyExists,
            "template_target_exists_use_force",
        ));
    }
    fs::create_dir_all(root.join("src"))?;
    let cargo_toml = render_cargo_toml(&options.name);
    let main_rs = render_main_rs(&kind, &options.name);
    let readme = render_readme(&kind, &options.name);

    write_with_force(root.join("Cargo.toml"), &cargo_toml, options.force)?;
    write_with_force(root.join("src/main.rs"), &main_rs, options.force)?;
    write_with_force(root.join("README.md"), &readme, options.force)?;

    Ok(TemplateScaffoldResult {
        template: kind.as_str().to_string(),
        root: root.display().to_string(),
        created_files: vec![
            root.join("Cargo.toml").display().to_string(),
            root.join("src/main.rs").display().to_string(),
            root.join("README.md").display().to_string(),
        ],
    })
}

fn write_with_force(path: PathBuf, body: &str, force: bool) -> io::Result<()> {
    if path.exists() && !force {
        return Err(io::Error::new(
            io::ErrorKind::AlreadyExists,
            format!("file_exists:{}", path.display()),
        ));
    }
    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent)?;
    }
    fs::write(path, body)
}

fn render_cargo_toml(name: &str) -> String {
    format!(
        r#"[package]
name = "{name}"
version = "0.1.0"
edition = "2021"

[dependencies]
infring-agent-surface = "0.1"
serde_json = "1"
"#
    )
}

fn render_main_rs(kind: &TemplateKind, _name: &str) -> String {
    match kind {
        TemplateKind::SingleAgent => single_agent_main(),
        TemplateKind::Swarm => swarm_main(),
        TemplateKind::Rag => rag_main(),
        TemplateKind::Voice => voice_main(),
    }
}

fn render_readme(kind: &TemplateKind, name: &str) -> String {
    format!(
        "# {}\n\nTemplate kind: `{}`\n\nThis scaffold was generated by `cargo run -p xtask -- infring-new`.\n",
        name,
        kind.as_str()
    )
}

fn single_agent_main() -> String {
    r#"use infring_agent_surface::{agent, AgentExecutionContext, ProviderClientRegistry};

fn main() {
    let providers = ProviderClientRegistry::with_builtin();
    let contract = agent!(
        "assistant",
        preamble = "You are a reliable assistant.",
        provider = "local-echo",
        tools = ["web.search", "memory.read"]
    )
    .initial_prompt("Give me one concise operational update.")
    .lifespan_seconds(3600)
    .build()
    .expect("valid agent contract");

    let ctx = AgentExecutionContext::new(&providers, None);
    let run = contract.run_once(&ctx).expect("provider run");
    println!("{}", run.response.output);
}
"#
    .to_string()
}

fn swarm_main() -> String {
    r#"use infring_agent_surface::{agent, AgentExecutionContext, ProviderClientRegistry};

fn main() {
    let providers = ProviderClientRegistry::with_builtin();
    let planner = agent!("planner").initial_prompt("Plan the task in three steps.").build().expect("planner");
    let worker = agent!("worker").initial_prompt("Execute the first step.").build().expect("worker");
    let ctx = AgentExecutionContext::new(&providers, None);
    let planner_run = planner.run_once(&ctx).expect("planner run");
    let worker_run = worker.run_once(&ctx).expect("worker run");
    println!("planner={}", planner_run.response.output);
    println!("worker={}", worker_run.response.output);
}
"#
    .to_string()
}

fn rag_main() -> String {
    r#"use infring_agent_surface::{agent, AgentExecutionContext, CapabilityPackCatalog, ProviderClientRegistry};

fn main() {
    let providers = ProviderClientRegistry::with_builtin();
    let packs = CapabilityPackCatalog::new();
    let contract = agent!("rag-agent")
        .capability_pack("research")
        .initial_prompt("Summarize the top findings from today's notes.")
        .build()
        .expect("rag agent");
    let ctx = AgentExecutionContext::new(&providers, Some(&packs));
    let run = contract.run_once(&ctx).expect("rag run");
    println!("{}", run.response.output);
}
"#
    .to_string()
}

fn voice_main() -> String {
    r#"use infring_agent_surface::{agent, AgentExecutionContext, ProviderClientRegistry};

fn main() {
    let providers = ProviderClientRegistry::with_builtin();
    let contract = agent!("voice-agent")
        .tool("voice.transcribe")
        .tool("voice.respond")
        .initial_prompt("Read the transcript and respond clearly.")
        .build()
        .expect("voice agent");
    let ctx = AgentExecutionContext::new(&providers, None);
    let run = contract.run_once(&ctx).expect("voice run");
    println!("{}", run.response.output);
}
"#
    .to_string()
}

pub fn default_template_dir(root: &Path) -> PathBuf {
    root.join("examples")
}

