const RULES: &[DiscoverRule] = &[
    DiscoverRule {
        pattern: r"^git\s+(?:-[Cc]\s+\S+\s+)*(status|log|diff|show|add|commit|push|pull|branch|fetch|stash|worktree)",
        canonical: "infring git",
        category: "Git",
        savings_pct: 70.0,
        subcmd_savings: &[("diff", 80.0), ("show", 80.0), ("add", 59.0), ("commit", 59.0)],
        subcmd_status: &[],
    },
    DiscoverRule {
        pattern: r"^gh\s+(pr|issue|run|repo|api|release)",
        canonical: "infring github",
        category: "GitHub",
        savings_pct: 82.0,
        subcmd_savings: &[("pr", 87.0), ("run", 82.0), ("issue", 80.0)],
        subcmd_status: &[],
    },
    DiscoverRule {
        pattern: r"^cargo\s+(build|test|clippy|check|fmt|install)",
        canonical: "infring cargo",
        category: "Cargo",
        savings_pct: 80.0,
        subcmd_savings: &[("test", 90.0), ("check", 80.0)],
        subcmd_status: &[("fmt", SupportStatus::Passthrough)],
    },
    DiscoverRule {
        pattern: r"^(cat|head|tail)\s+",
        canonical: "infring read",
        category: "Files",
        savings_pct: 60.0,
        subcmd_savings: &[],
        subcmd_status: &[],
    },
    DiscoverRule {
        pattern: r"^(rg|grep)\s+",
        canonical: "infring grep",
        category: "Files",
        savings_pct: 75.0,
        subcmd_savings: &[],
        subcmd_status: &[],
    },
    DiscoverRule {
        pattern: r"^ls(\s|$)",
        canonical: "infring ls",
        category: "Files",
        savings_pct: 65.0,
        subcmd_savings: &[],
        subcmd_status: &[],
    },
    DiscoverRule {
        pattern: r"^find\s+",
        canonical: "infring find",
        category: "Files",
        savings_pct: 70.0,
        subcmd_savings: &[],
        subcmd_status: &[],
    },
    DiscoverRule {
        pattern: r"^tree(\s|$)",
        canonical: "infring tree",
        category: "Files",
        savings_pct: 70.0,
        subcmd_savings: &[],
        subcmd_status: &[],
    },
    DiscoverRule {
        pattern: r"^diff\s+",
        canonical: "infring diff",
        category: "Files",
        savings_pct: 60.0,
        subcmd_savings: &[],
        subcmd_status: &[],
    },
    DiscoverRule {
        pattern: r"^curl\s+",
        canonical: "infring web fetch",
        category: "Network",
        savings_pct: 70.0,
        subcmd_savings: &[],
        subcmd_status: &[],
    },
    DiscoverRule {
        pattern: r"^wget\s+",
        canonical: "infring web fetch",
        category: "Network",
        savings_pct: 65.0,
        subcmd_savings: &[],
        subcmd_status: &[],
    },
    DiscoverRule {
        pattern: r"^(pnpm|npm|npx)\s+",
        canonical: "infring npm",
        category: "PackageManager",
        savings_pct: 70.0,
        subcmd_savings: &[],
        subcmd_status: &[],
    },
    DiscoverRule {
        pattern: r"^(python\s+-m\s+)?pytest(\s|$)",
        canonical: "infring pytest",
        category: "Tests",
        savings_pct: 90.0,
        subcmd_savings: &[],
        subcmd_status: &[],
    },
    DiscoverRule {
        pattern: r"^ruff\s+(check|format)",
        canonical: "infring ruff",
        category: "Python",
        savings_pct: 80.0,
        subcmd_savings: &[("format", 75.0), ("check", 80.0)],
        subcmd_status: &[],
    },
    DiscoverRule {
        pattern: r"^docker\s+(ps|images|logs|run|exec|build|compose\s+(ps|logs|build))",
        canonical: "infring docker",
        category: "Infra",
        savings_pct: 85.0,
        subcmd_savings: &[],
        subcmd_status: &[],
    },
    DiscoverRule {
        pattern: r"^kubectl\s+(get|logs|describe|apply)",
        canonical: "infring kubectl",
        category: "Infra",
        savings_pct: 85.0,
        subcmd_savings: &[],
        subcmd_status: &[],
    },
];

const IGNORED_EXACT: &[&str] = &["", "exit", "clear", "pwd", "history", "reset"];
const IGNORED_PREFIXES: &[&str] = &["echo ", "printf ", "export ", "alias "];
