include_parts!(
    "autonomy_controller_parts/010-prelude-and-state.rs",
    "autonomy_controller_parts/020-hand-operations.rs",
    "autonomy_controller_parts/030-ephemeral-and-trunk.rs",
    "autonomy_controller_parts/050-proactive-daemon-dream-speculation.rs",
    "autonomy_controller_parts/052-autoreason.rs",
    "autonomy_controller_parts/051-speculation-and-regression-tests.rs",
    "autonomy_controller_parts/040-command-dispatch.rs",
);
