include_parts!(
    "canyon_plane_parts/010-footprint-no-std-ready.rs",
    "canyon_plane_parts/020-efficiency-command.rs",
    "canyon_plane_parts/030-evolution-command.rs",
    "canyon_plane_parts/040-sandbox-command.rs",
    "canyon_plane_parts/050-ecosystem-command.rs",
    "canyon_plane_parts/060-workflow-command.rs",
    "canyon_plane_parts/070-benchmark-gate-command.rs",
);
