include_parts!(
    "health_status_parts/010-receipt-hash.rs",
    "health_status_parts/020-audit-cron-delivery.rs",
    "health_status_parts/030-collect-dopamine-ambient-dashboard-metric.rs",
    "health_status_parts/040-collect-assimilation-pain-dashboard-metric.rs",
    "health_status_parts/050-collect-vbrowser-dashboard-metric.rs",
    "health_status_parts/060-collect-dashboard-metrics.rs",
    "health_status_parts/070-write-text.rs",
);
