include_parts!(
    "metakernel_parts/010-state-root.rs",
    "metakernel_parts/020-validate-world-registry-payload.rs",
    "metakernel_parts/030-run-budget-admission.rs",
    "metakernel_parts/040-run-quantum-broker.rs",
    "metakernel_parts/050-run-execution-profiles.rs",
    "metakernel_parts/055-run-microkernel-safety.rs",
    "metakernel_parts/057-digital-dna-foundation.rs",
    "metakernel_parts/058-hybrid-digital-dna-v2.rs",
    "metakernel_parts/060-run.rs",
);
