include_parts!(
    "orchestration_parts/010-print-json-line.rs",
    "orchestration_parts/020-validate-finding.rs",
    "orchestration_parts/030-detect-scope-overlaps.rs",
    "orchestration_parts/040-load-task-group.rs",
    "orchestration_parts/050-maybe-checkpoint.rs",
    "orchestration_parts/060-retrieve-partial-results.rs",
    "orchestration_parts/070-run-coordinator.rs",
    "orchestration_parts/080-invoke.rs",
    "orchestration_parts/090-tests.rs",
);
