include!("skills_plane_parts/part_000.rs");
include!("skills_plane_parts/part_001.rs");
include!("skills_plane_parts/part_002.rs");
include!("skills_plane_parts/part_003.rs");
include!("skills_plane_parts/part_004.rs");
include!("skills_plane_parts/part_005.rs");
include!("skills_plane_parts/part_006.rs");
include!("skills_plane_parts/part_007.rs");
include!("skills_plane_parts/part_008.rs");
