include_parts!(
    "spine_parts/010-stable-hash.rs",
    "spine_parts/020-parse-json-payload.rs",
    "spine_parts/030-parse-worktree-blocks.rs",
    "spine_parts/040-run-sleep-cleanup-command.rs",
    "spine_parts/050-build-claim-evidence.rs",
    "spine_parts/060-execute-native.rs",
    "spine_parts/070-parity-fixture-evidence-plan-matches-ts-rules.rs",
);
