    #[test]
    fn dashboard_troubleshooting_outbox_state_lane_reports_depth_and_histogram() {
        let root = tempfile::tempdir().expect("tempdir");
        let report = run_action(
            root.path(),
            "dashboard.troubleshooting.report_message",
            &json!({
                "source":"dashboard_report_popup",
                "session_id":"session-outbox-state",
                "message_id":"msg-outbox-state",
                "__github_issue_mock_auth_missing": true
            }),
        );
        assert!(report.ok);
        let lane = run_action(
            root.path(),
            "dashboard.troubleshooting.outbox.state",
            &json!({"limit": 10}),
        );
        assert!(lane.ok);
        let payload = lane.payload.unwrap_or_else(|| json!({}));
        assert_eq!(
            payload.get("type").and_then(Value::as_str),
            Some("dashboard_troubleshooting_outbox_state")
        );
        assert_eq!(payload.get("depth").and_then(Value::as_i64), Some(1));
        assert!(
            payload
                .pointer("/error_histogram")
                .and_then(Value::as_array)
                .is_some()
        );
        assert_eq!(
            payload
                .pointer("/queue_pressure_contract/version")
                .and_then(Value::as_str),
            Some("v1")
        );
        assert!(
            payload
                .pointer("/queue_pressure_contract/snapshot_epoch_s")
                .and_then(Value::as_i64)
                .unwrap_or(0)
                > 0
        );
        assert_eq!(
            payload
                .pointer("/queue_pressure_contract/family")
                .and_then(Value::as_str),
            Some("dashboard_queue_pressure_contract_v1")
        );
        assert_eq!(
            payload
                .pointer("/queue_pressure_contract/producer")
                .and_then(Value::as_str),
            Some("dashboard.troubleshooting")
        );
        assert_eq!(
            payload
                .get("queue_pressure_contract_family")
                .and_then(Value::as_str),
            Some("dashboard_queue_pressure_contract_v1")
        );
        assert_eq!(
            payload
                .pointer("/queue_pressure_contract/priority")
                .and_then(Value::as_str),
            payload
                .get("queue_pressure_priority")
                .and_then(Value::as_str)
        );
        assert_eq!(
            payload
                .pointer("/queue_pressure_contract/action_hint")
                .and_then(Value::as_str),
            payload
                .get("queue_pressure_action_hint")
                .and_then(Value::as_str)
        );
        assert_eq!(
            payload
                .pointer("/queue_pressure_contract/escalation_lane")
                .and_then(Value::as_str),
            payload
                .get("queue_pressure_escalation_lane")
                .and_then(Value::as_str)
        );
        assert_eq!(
            payload
                .pointer("/queue_pressure_contract/runbook_id")
                .and_then(Value::as_str),
            payload
                .get("queue_pressure_runbook_id")
                .and_then(Value::as_str)
        );
        assert_eq!(
            payload
                .pointer("/queue_pressure_contract/escalation_owner")
                .and_then(Value::as_str),
            payload
                .get("queue_pressure_escalation_owner")
                .and_then(Value::as_str)
        );
        assert_eq!(
            payload
                .pointer("/queue_pressure_contract/deadline_epoch_s")
                .and_then(Value::as_i64),
            payload
                .get("queue_pressure_deadline_epoch_s")
                .and_then(Value::as_i64)
        );
        assert_eq!(
            payload
                .pointer("/queue_pressure_contract/breach_reason")
                .and_then(Value::as_str),
            payload
                .get("queue_pressure_breach_reason")
                .and_then(Value::as_str)
        );
        assert_eq!(
            payload
                .pointer("/queue_pressure_contract/blocking_kind")
                .and_then(Value::as_str),
            payload
                .get("queue_pressure_blocking_kind")
                .and_then(Value::as_str)
        );
        assert_eq!(
            payload
                .pointer("/queue_pressure_contract/auto_retry_allowed")
                .and_then(Value::as_bool),
            payload
                .get("queue_pressure_auto_retry_allowed")
                .and_then(Value::as_bool)
        );
        assert_eq!(
            payload
                .pointer("/queue_pressure_contract/execution_policy")
                .and_then(Value::as_str),
            payload
                .get("queue_pressure_execution_policy")
                .and_then(Value::as_str)
        );
        assert_eq!(
            payload
                .pointer("/queue_pressure_contract/manual_gate_required")
                .and_then(Value::as_bool),
            payload
                .get("queue_pressure_manual_gate_required")
                .and_then(Value::as_bool)
        );
        assert_eq!(
            payload
                .pointer("/queue_pressure_contract/manual_gate_reason")
                .and_then(Value::as_str),
            payload
                .get("queue_pressure_manual_gate_reason")
                .and_then(Value::as_str)
        );
        assert_eq!(
            payload
                .pointer("/queue_pressure_contract/requeue_strategy")
                .and_then(Value::as_str),
            payload
                .get("queue_pressure_requeue_strategy")
                .and_then(Value::as_str)
        );
        assert_eq!(
            payload
                .pointer("/queue_pressure_contract/can_execute_without_human")
                .and_then(Value::as_bool),
            payload
                .get("queue_pressure_can_execute_without_human")
                .and_then(Value::as_bool)
        );
        assert_eq!(
            payload
                .pointer("/queue_pressure_contract/execution_window")
                .and_then(Value::as_str),
            payload
                .get("queue_pressure_execution_window")
                .and_then(Value::as_str)
        );
        assert_eq!(
            payload
                .pointer("/queue_pressure_contract/manual_gate_timeout_seconds")
                .and_then(Value::as_i64),
            payload
                .get("queue_pressure_manual_gate_timeout_seconds")
                .and_then(Value::as_i64)
        );
        assert_eq!(
            payload
                .pointer("/queue_pressure_contract/next_action_after_seconds")
                .and_then(Value::as_i64),
            payload
                .get("queue_pressure_next_action_after_seconds")
                .and_then(Value::as_i64)
        );
        assert_eq!(
            payload
                .pointer("/queue_pressure_contract/next_action_kind")
                .and_then(Value::as_str),
            payload
                .get("queue_pressure_next_action_kind")
                .and_then(Value::as_str)
        );
        assert_eq!(
            payload
                .pointer("/queue_pressure_contract/retry_window_class")
                .and_then(Value::as_str),
            payload
                .get("queue_pressure_retry_window_class")
                .and_then(Value::as_str)
        );
        assert_eq!(
            payload
                .pointer("/queue_pressure_contract/readiness_state")
                .and_then(Value::as_str),
            payload
                .get("queue_pressure_readiness_state")
                .and_then(Value::as_str)
        );
        assert_eq!(
            payload
                .pointer("/queue_pressure_contract/readiness_reason")
                .and_then(Value::as_str),
            payload
                .get("queue_pressure_readiness_reason")
                .and_then(Value::as_str)
        );
        assert_eq!(
            payload
                .pointer("/queue_pressure_contract/automation_safe")
                .and_then(Value::as_bool),
            payload
                .get("queue_pressure_automation_safe")
                .and_then(Value::as_bool)
        );
        assert_eq!(
            payload.pointer("/queue_pressure_contract/decision_vector"),
            payload.get("queue_pressure_decision_vector")
        );
        assert_eq!(
            payload
                .pointer("/queue_pressure_contract/decision_vector_key")
                .and_then(Value::as_str),
            payload
                .get("queue_pressure_decision_vector_key")
                .and_then(Value::as_str)
        );
        assert_eq!(
            payload
                .pointer("/queue_pressure_contract/decision_vector/decision_vector_key")
                .and_then(Value::as_str),
            payload
                .get("queue_pressure_decision_vector_key")
                .and_then(Value::as_str)
        );
        assert_eq!(
            payload
                .pointer("/queue_pressure_contract/decision_route_hint")
                .and_then(Value::as_str),
            payload
                .get("queue_pressure_decision_route_hint")
                .and_then(Value::as_str)
        );
        assert_eq!(
            payload
                .pointer("/queue_pressure_contract/decision_urgency_tier")
                .and_then(Value::as_str),
            payload
                .get("queue_pressure_decision_urgency_tier")
                .and_then(Value::as_str)
        );
        assert_eq!(
            payload
                .pointer("/queue_pressure_contract/decision_retry_budget_class")
                .and_then(Value::as_str),
            payload
                .get("queue_pressure_decision_retry_budget_class")
                .and_then(Value::as_str)
        );
        assert_eq!(
            payload
                .pointer("/queue_pressure_contract/decision_lane_token")
                .and_then(Value::as_str),
            payload
                .get("queue_pressure_decision_lane_token")
                .and_then(Value::as_str)
        );
        assert_eq!(
            payload
                .pointer("/queue_pressure_contract/decision_dispatch_mode")
                .and_then(Value::as_str),
            payload
                .get("queue_pressure_decision_dispatch_mode")
                .and_then(Value::as_str)
        );
        assert_eq!(
            payload
                .pointer("/queue_pressure_contract/decision_manual_ack_required")
                .and_then(Value::as_bool),
            payload
                .get("queue_pressure_decision_manual_ack_required")
                .and_then(Value::as_bool)
        );
        assert_eq!(
            payload
                .pointer("/queue_pressure_contract/decision_execution_guard")
                .and_then(Value::as_str),
            payload
                .get("queue_pressure_decision_execution_guard")
                .and_then(Value::as_str)
        );
        assert_eq!(
            payload
                .pointer("/queue_pressure_contract/decision_followup_required")
                .and_then(Value::as_bool),
            payload
                .get("queue_pressure_decision_followup_required")
                .and_then(Value::as_bool)
        );
        assert_eq!(
            payload
                .pointer("/queue_pressure_contract/decision_vector/execution_guard")
                .and_then(Value::as_str),
            payload
                .get("queue_pressure_decision_execution_guard")
                .and_then(Value::as_str)
        );
        assert_eq!(
            payload
                .pointer("/queue_pressure_contract/decision_vector/followup_required")
                .and_then(Value::as_bool),
            payload
                .get("queue_pressure_decision_followup_required")
                .and_then(Value::as_bool)
        );
        assert_eq!(
            payload
                .pointer("/queue_pressure_contract/decision_vector_version")
                .and_then(Value::as_str),
            payload
                .get("queue_pressure_decision_vector_version")
                .and_then(Value::as_str)
        );
    }

