    #[test]
    fn dashboard_troubleshooting_pressure_contract_object_aliases_route_with_parity() {
        let root = tempfile::tempdir().expect("tempdir");

        let outbox_base = run_action(
            root.path(),
            "dashboard.troubleshooting.outbox.state",
            &json!({"limit": 10}),
        );
        let outbox_alias = run_action(
            root.path(),
            "dashboard.troubleshooting.outbox.pressure.contract_object",
            &json!({"limit": 10}),
        );
        assert!(outbox_base.ok);
        assert!(outbox_alias.ok);
        let outbox_base_payload = outbox_base.payload.unwrap_or_else(|| json!({}));
        let outbox_alias_payload = outbox_alias.payload.unwrap_or_else(|| json!({}));
        assert_eq!(
            outbox_base_payload
                .pointer("/queue_pressure_contract/version")
                .and_then(Value::as_str),
            outbox_alias_payload
                .pointer("/queue_pressure_contract/version")
                .and_then(Value::as_str)
        );
        assert_eq!(
            outbox_base_payload
                .pointer("/queue_pressure_contract/snapshot_epoch_s")
                .and_then(Value::as_i64),
            outbox_alias_payload
                .pointer("/queue_pressure_contract/snapshot_epoch_s")
                .and_then(Value::as_i64)
        );
        assert_eq!(
            outbox_base_payload
                .pointer("/queue_pressure_contract/family")
                .and_then(Value::as_str),
            outbox_alias_payload
                .pointer("/queue_pressure_contract/family")
                .and_then(Value::as_str)
        );
        assert_eq!(
            outbox_base_payload
                .pointer("/queue_pressure_contract/priority")
                .and_then(Value::as_str),
            outbox_alias_payload
                .pointer("/queue_pressure_contract/priority")
                .and_then(Value::as_str)
        );
        assert_eq!(
            outbox_base_payload
                .pointer("/queue_pressure_contract/action_hint")
                .and_then(Value::as_str),
            outbox_alias_payload
                .pointer("/queue_pressure_contract/action_hint")
                .and_then(Value::as_str)
        );
        assert_eq!(
            outbox_base_payload
                .pointer("/queue_pressure_contract/escalation_lane")
                .and_then(Value::as_str),
            outbox_alias_payload
                .pointer("/queue_pressure_contract/escalation_lane")
                .and_then(Value::as_str)
        );
        assert_eq!(
            outbox_base_payload
                .pointer("/queue_pressure_contract/runbook_id")
                .and_then(Value::as_str),
            outbox_alias_payload
                .pointer("/queue_pressure_contract/runbook_id")
                .and_then(Value::as_str)
        );
        assert_eq!(
            outbox_base_payload
                .pointer("/queue_pressure_contract/deadline_epoch_s")
                .and_then(Value::as_i64),
            outbox_alias_payload
                .pointer("/queue_pressure_contract/deadline_epoch_s")
                .and_then(Value::as_i64)
        );
        assert_eq!(
            outbox_base_payload
                .pointer("/queue_pressure_contract/breach_reason")
                .and_then(Value::as_str),
            outbox_alias_payload
                .pointer("/queue_pressure_contract/breach_reason")
                .and_then(Value::as_str)
        );
        assert_eq!(
            outbox_base_payload
                .pointer("/queue_pressure_contract/blocking_kind")
                .and_then(Value::as_str),
            outbox_alias_payload
                .pointer("/queue_pressure_contract/blocking_kind")
                .and_then(Value::as_str)
        );
        assert_eq!(
            outbox_base_payload
                .pointer("/queue_pressure_contract/auto_retry_allowed")
                .and_then(Value::as_bool),
            outbox_alias_payload
                .pointer("/queue_pressure_contract/auto_retry_allowed")
                .and_then(Value::as_bool)
        );
        assert_eq!(
            outbox_base_payload
                .pointer("/queue_pressure_contract/execution_policy")
                .and_then(Value::as_str),
            outbox_alias_payload
                .pointer("/queue_pressure_contract/execution_policy")
                .and_then(Value::as_str)
        );
        assert_eq!(
            outbox_base_payload
                .pointer("/queue_pressure_contract/manual_gate_required")
                .and_then(Value::as_bool),
            outbox_alias_payload
                .pointer("/queue_pressure_contract/manual_gate_required")
                .and_then(Value::as_bool)
        );
        assert_eq!(
            outbox_base_payload
                .pointer("/queue_pressure_contract/manual_gate_reason")
                .and_then(Value::as_str),
            outbox_alias_payload
                .pointer("/queue_pressure_contract/manual_gate_reason")
                .and_then(Value::as_str)
        );
        assert_eq!(
            outbox_base_payload
                .pointer("/queue_pressure_contract/requeue_strategy")
                .and_then(Value::as_str),
            outbox_alias_payload
                .pointer("/queue_pressure_contract/requeue_strategy")
                .and_then(Value::as_str)
        );
        assert_eq!(
            outbox_base_payload
                .pointer("/queue_pressure_contract/can_execute_without_human")
                .and_then(Value::as_bool),
            outbox_alias_payload
                .pointer("/queue_pressure_contract/can_execute_without_human")
                .and_then(Value::as_bool)
        );
        assert_eq!(
            outbox_base_payload
                .pointer("/queue_pressure_contract/execution_window")
                .and_then(Value::as_str),
            outbox_alias_payload
                .pointer("/queue_pressure_contract/execution_window")
                .and_then(Value::as_str)
        );
        assert_eq!(
            outbox_base_payload
                .pointer("/queue_pressure_contract/manual_gate_timeout_seconds")
                .and_then(Value::as_i64),
            outbox_alias_payload
                .pointer("/queue_pressure_contract/manual_gate_timeout_seconds")
                .and_then(Value::as_i64)
        );

        let summary_base = run_action(
            root.path(),
            "dashboard.troubleshooting.summary",
            &json!({"limit": 10}),
        );
        let summary_alias = run_action(
            root.path(),
            "dashboard.troubleshooting.summary.pressure.contract_object",
            &json!({"limit": 10}),
        );
        assert!(summary_base.ok);
        assert!(summary_alias.ok);
        let summary_base_payload = summary_base.payload.unwrap_or_else(|| json!({}));
        let summary_alias_payload = summary_alias.payload.unwrap_or_else(|| json!({}));
        assert_eq!(
            summary_base_payload
                .pointer("/queues/outbox_health/queue_pressure_contract/version")
                .and_then(Value::as_str),
            summary_alias_payload
                .pointer("/queues/outbox_health/queue_pressure_contract/version")
                .and_then(Value::as_str)
        );
        assert_eq!(
            summary_base_payload
                .pointer("/queues/outbox_health/queue_pressure_contract/snapshot_epoch_s")
                .and_then(Value::as_i64),
            summary_alias_payload
                .pointer("/queues/outbox_health/queue_pressure_contract/snapshot_epoch_s")
                .and_then(Value::as_i64)
        );
        assert_eq!(
            summary_base_payload
                .pointer("/queues/outbox_health/queue_pressure_contract/family")
                .and_then(Value::as_str),
            summary_alias_payload
                .pointer("/queues/outbox_health/queue_pressure_contract/family")
                .and_then(Value::as_str)
        );
        assert_eq!(
            summary_base_payload
                .pointer("/queues/outbox_health/queue_pressure_contract/priority")
                .and_then(Value::as_str),
            summary_alias_payload
                .pointer("/queues/outbox_health/queue_pressure_contract/priority")
                .and_then(Value::as_str)
        );
        assert_eq!(
            summary_base_payload
                .pointer("/queues/outbox_health/queue_pressure_contract/action_hint")
                .and_then(Value::as_str),
            summary_alias_payload
                .pointer("/queues/outbox_health/queue_pressure_contract/action_hint")
                .and_then(Value::as_str)
        );
        assert_eq!(
            summary_base_payload
                .pointer("/queues/outbox_health/queue_pressure_contract/escalation_lane")
                .and_then(Value::as_str),
            summary_alias_payload
                .pointer("/queues/outbox_health/queue_pressure_contract/escalation_lane")
                .and_then(Value::as_str)
        );
        assert_eq!(
            summary_base_payload
                .pointer("/queues/outbox_health/queue_pressure_contract/runbook_id")
                .and_then(Value::as_str),
            summary_alias_payload
                .pointer("/queues/outbox_health/queue_pressure_contract/runbook_id")
                .and_then(Value::as_str)
        );
        assert_eq!(
            summary_base_payload
                .pointer("/queues/outbox_health/queue_pressure_contract/deadline_epoch_s")
                .and_then(Value::as_i64),
            summary_alias_payload
                .pointer("/queues/outbox_health/queue_pressure_contract/deadline_epoch_s")
                .and_then(Value::as_i64)
        );
        assert_eq!(
            summary_base_payload
                .pointer("/queues/outbox_health/queue_pressure_contract/breach_reason")
                .and_then(Value::as_str),
            summary_alias_payload
                .pointer("/queues/outbox_health/queue_pressure_contract/breach_reason")
                .and_then(Value::as_str)
        );
        assert_eq!(
            summary_base_payload
                .pointer("/queues/outbox_health/queue_pressure_contract/blocking_kind")
                .and_then(Value::as_str),
            summary_alias_payload
                .pointer("/queues/outbox_health/queue_pressure_contract/blocking_kind")
                .and_then(Value::as_str)
        );
        assert_eq!(
            summary_base_payload
                .pointer("/queues/outbox_health/queue_pressure_contract/auto_retry_allowed")
                .and_then(Value::as_bool),
            summary_alias_payload
                .pointer("/queues/outbox_health/queue_pressure_contract/auto_retry_allowed")
                .and_then(Value::as_bool)
        );
        assert_eq!(
            summary_base_payload
                .pointer("/queues/outbox_health/queue_pressure_contract/execution_policy")
                .and_then(Value::as_str),
            summary_alias_payload
                .pointer("/queues/outbox_health/queue_pressure_contract/execution_policy")
                .and_then(Value::as_str)
        );
        assert_eq!(
            summary_base_payload
                .pointer("/queues/outbox_health/queue_pressure_contract/manual_gate_required")
                .and_then(Value::as_bool),
            summary_alias_payload
                .pointer("/queues/outbox_health/queue_pressure_contract/manual_gate_required")
                .and_then(Value::as_bool)
        );
        assert_eq!(
            summary_base_payload
                .pointer("/queues/outbox_health/queue_pressure_contract/manual_gate_reason")
                .and_then(Value::as_str),
            summary_alias_payload
                .pointer("/queues/outbox_health/queue_pressure_contract/manual_gate_reason")
                .and_then(Value::as_str)
        );
        assert_eq!(
            summary_base_payload
                .pointer("/queues/outbox_health/queue_pressure_contract/requeue_strategy")
                .and_then(Value::as_str),
            summary_alias_payload
                .pointer("/queues/outbox_health/queue_pressure_contract/requeue_strategy")
                .and_then(Value::as_str)
        );
        assert_eq!(
            summary_base_payload
                .pointer("/queues/outbox_health/queue_pressure_contract/can_execute_without_human")
                .and_then(Value::as_bool),
            summary_alias_payload
                .pointer("/queues/outbox_health/queue_pressure_contract/can_execute_without_human")
                .and_then(Value::as_bool)
        );
        assert_eq!(
            summary_base_payload
                .pointer("/queues/outbox_health/queue_pressure_contract/execution_window")
                .and_then(Value::as_str),
            summary_alias_payload
                .pointer("/queues/outbox_health/queue_pressure_contract/execution_window")
                .and_then(Value::as_str)
        );
        assert_eq!(
            summary_base_payload
                .pointer("/queues/outbox_health/queue_pressure_contract/manual_gate_timeout_seconds")
                .and_then(Value::as_i64),
            summary_alias_payload
                .pointer("/queues/outbox_health/queue_pressure_contract/manual_gate_timeout_seconds")
                .and_then(Value::as_i64)
        );
    }

