
#[test]
fn search_unknown_provider_fail_closed_includes_retry_strategy() {
    let out = api_search(
        tempfile::tempdir().expect("tempdir").path(),
        &json!({
            "query": "agent frameworks docs",
            "provider": "definitely-not-a-provider"
        }),
    );
    assert_eq!(
        out.get("error").and_then(Value::as_str),
        Some("unknown_search_provider")
    );
    assert_eq!(
        out.pointer("/retry/recommended").and_then(Value::as_bool),
        Some(true)
    );
    assert_eq!(
        out.pointer("/retry/strategy").and_then(Value::as_str),
        Some("use_supported_provider_or_auto")
    );
    assert_eq!(
        out.pointer("/retry/reason").and_then(Value::as_str),
        Some("unknown_search_provider")
    );
    assert_eq!(
        out.pointer("/retry/contract_version").and_then(Value::as_str),
        Some("v1")
    );
    assert_eq!(
        out.pointer("/retry/contract_family").and_then(Value::as_str),
        Some("web_retry_contract_v1")
    );
    assert_eq!(
        out.pointer("/retry/recovery_mode").and_then(Value::as_str),
        Some("switch_provider")
    );
    assert_eq!(
        out.pointer("/retry/priority").and_then(Value::as_str),
        Some("medium")
    );
    assert_eq!(
        out.pointer("/retry/operator_action_hint")
            .and_then(Value::as_str),
        Some("set_provider_auto_or_supported_provider")
    );
    assert_eq!(
        out.pointer("/retry/operator_owner").and_then(Value::as_str),
        Some("operator")
    );
    assert_eq!(
        out.pointer("/retry/diagnostic_code").and_then(Value::as_str),
        Some("search_retry_unknown_search_provider")
    );
    assert_eq!(
        out.pointer("/retry/blocking_kind").and_then(Value::as_str),
        Some("provider_configuration_required")
    );
    assert_eq!(
        out.pointer("/retry/auto_retry_allowed")
            .and_then(Value::as_bool),
        Some(true)
    );
    assert_eq!(
        out.pointer("/retry/retryable").and_then(Value::as_bool),
        Some(true)
    );
    assert_eq!(
        out.pointer("/retry/idempotent").and_then(Value::as_bool),
        Some(true)
    );
    assert_eq!(
        out.pointer("/retry/category").and_then(Value::as_str),
        Some("validation")
    );
    assert_eq!(
        out.pointer("/retry/lane").and_then(Value::as_str),
        Some("web_search")
    );
}

#[test]
fn search_conflicting_time_filters_includes_retry_strategy() {
    let out = api_search(
        tempfile::tempdir().expect("tempdir").path(),
        &json!({
            "query": "agent frameworks",
            "freshness": "week",
            "date_before": "2026-04-10"
        }),
    );
    assert_eq!(
        out.get("error").and_then(Value::as_str),
        Some("conflicting_time_filters")
    );
    assert_eq!(
        out.pointer("/retry/strategy").and_then(Value::as_str),
        Some("remove_conflicting_time_filters")
    );
    assert_eq!(
        out.pointer("/retry/reason").and_then(Value::as_str),
        Some("conflicting_time_filters")
    );
    assert_eq!(
        out.pointer("/retry/contract_version").and_then(Value::as_str),
        Some("v1")
    );
    assert_eq!(
        out.pointer("/retry/contract_family").and_then(Value::as_str),
        Some("web_retry_contract_v1")
    );
    assert_eq!(
        out.pointer("/retry/recovery_mode").and_then(Value::as_str),
        Some("adjust_filters")
    );
    assert_eq!(
        out.pointer("/retry/priority").and_then(Value::as_str),
        Some("medium")
    );
    assert_eq!(
        out.pointer("/retry/operator_action_hint")
            .and_then(Value::as_str),
        Some("remove_freshness_or_date_range_conflict")
    );
    assert_eq!(
        out.pointer("/retry/operator_owner").and_then(Value::as_str),
        Some("user")
    );
    assert_eq!(
        out.pointer("/retry/diagnostic_code").and_then(Value::as_str),
        Some("search_retry_conflicting_time_filters")
    );
    assert_eq!(
        out.pointer("/retry/blocking_kind").and_then(Value::as_str),
        Some("input_adjustment_required")
    );
    assert_eq!(
        out.pointer("/retry/auto_retry_allowed")
            .and_then(Value::as_bool),
        Some(false)
    );
    assert_eq!(
        out.pointer("/retry/retryable").and_then(Value::as_bool),
        Some(true)
    );
    assert_eq!(
        out.pointer("/retry/idempotent").and_then(Value::as_bool),
        Some(true)
    );
    assert_eq!(
        out.pointer("/retry/category").and_then(Value::as_str),
        Some("validation")
    );
    assert_eq!(
        out.pointer("/retry/lane").and_then(Value::as_str),
        Some("web_search")
    );
}

#[test]
fn fetch_unknown_provider_fail_closed_includes_retry_strategy() {
    let out = execute_fetch_request(
        tempfile::tempdir().expect("tempdir").path(),
        &json!({
            "url": "https://example.com",
            "provider": "definitely-not-fetch-provider"
        }),
    );
    assert_eq!(
        out.get("error").and_then(Value::as_str),
        Some("unknown_fetch_provider")
    );
    assert_eq!(
        out.pointer("/retry/recommended").and_then(Value::as_bool),
        Some(true)
    );
    assert_eq!(
        out.pointer("/retry/strategy").and_then(Value::as_str),
        Some("use_supported_provider_or_auto")
    );
    assert_eq!(
        out.pointer("/retry/reason").and_then(Value::as_str),
        Some("unknown_fetch_provider")
    );
    assert_eq!(
        out.pointer("/retry/contract_version").and_then(Value::as_str),
        Some("v1")
    );
    assert_eq!(
        out.pointer("/retry/contract_family").and_then(Value::as_str),
        Some("web_retry_contract_v1")
    );
    assert_eq!(
        out.pointer("/retry/recovery_mode").and_then(Value::as_str),
        Some("switch_provider")
    );
    assert_eq!(
        out.pointer("/retry/priority").and_then(Value::as_str),
        Some("medium")
    );
    assert_eq!(
        out.pointer("/retry/operator_action_hint")
            .and_then(Value::as_str),
        Some("set_fetch_provider_auto_or_supported_provider")
    );
    assert_eq!(
        out.pointer("/retry/operator_owner").and_then(Value::as_str),
        Some("operator")
    );
    assert_eq!(
        out.pointer("/retry/diagnostic_code").and_then(Value::as_str),
        Some("fetch_retry_unknown_fetch_provider")
    );
    assert_eq!(
        out.pointer("/retry/blocking_kind").and_then(Value::as_str),
        Some("provider_configuration_required")
    );
    assert_eq!(
        out.pointer("/retry/auto_retry_allowed")
            .and_then(Value::as_bool),
        Some(true)
    );
    assert_eq!(
        out.pointer("/retry/retryable").and_then(Value::as_bool),
        Some(true)
    );
    assert_eq!(
        out.pointer("/retry/idempotent").and_then(Value::as_bool),
        Some(true)
    );
    assert_eq!(
        out.pointer("/retry/category").and_then(Value::as_str),
        Some("validation")
    );
    assert_eq!(
        out.pointer("/retry/lane").and_then(Value::as_str),
        Some("web_fetch")
    );
}
