
#[test]
fn search_retry_envelope_helper_supports_unsupported_filter_contract() {
    let retry = search_retry_envelope_for_error("unsupported_search_filter");
    assert_eq!(
        retry.get("strategy").and_then(Value::as_str),
        Some("remove_unsupported_filter")
    );
    assert_eq!(
        retry.get("reason").and_then(Value::as_str),
        Some("unsupported_search_filter")
    );
    assert_eq!(
        retry.get("contract_version").and_then(Value::as_str),
        Some("v1")
    );
    assert_eq!(
        retry.get("contract_family").and_then(Value::as_str),
        Some("web_retry_contract_v1")
    );
    assert_eq!(
        retry.get("recovery_mode").and_then(Value::as_str),
        Some("adjust_filters")
    );
    assert_eq!(
        retry.get("priority").and_then(Value::as_str),
        Some("medium")
    );
    assert_eq!(
        retry.get("operator_action_hint").and_then(Value::as_str),
        Some("remove_or_replace_unsupported_filter")
    );
    assert_eq!(
        retry.get("operator_owner").and_then(Value::as_str),
        Some("user")
    );
    assert_eq!(
        retry.get("diagnostic_code").and_then(Value::as_str),
        Some("search_retry_unsupported_search_filter")
    );
    assert_eq!(
        retry.get("blocking_kind").and_then(Value::as_str),
        Some("input_adjustment_required")
    );
    assert_eq!(
        retry.get("auto_retry_allowed").and_then(Value::as_bool),
        Some(false)
    );
    assert_eq!(
        retry.get("escalation_lane").and_then(Value::as_str),
        Some("user_input")
    );
    assert_eq!(
        retry
            .get("requires_manual_confirmation")
            .and_then(Value::as_bool),
        Some(true)
    );
    assert_eq!(
        retry.get("execution_policy").and_then(Value::as_str),
        Some("manual_gate_required")
    );
    assert_eq!(
        retry.get("manual_gate_reason").and_then(Value::as_str),
        Some("input_adjustment_required")
    );
    assert_eq!(
        retry.get("requeue_strategy").and_then(Value::as_str),
        Some("manual")
    );
    assert_eq!(
        retry.get("can_execute_without_human").and_then(Value::as_bool),
        Some(false)
    );
    assert_eq!(
        retry.get("execution_window").and_then(Value::as_str),
        Some("after_manual_gate")
    );
    assert_eq!(
        retry
            .get("manual_gate_timeout_seconds")
            .and_then(Value::as_i64),
        Some(1800)
    );
    assert_eq!(
        retry.get("next_action_after_seconds").and_then(Value::as_i64),
        Some(1800)
    );
    assert_eq!(
        retry.get("next_action_kind").and_then(Value::as_str),
        Some("manual_gate")
    );
    assert_eq!(
        retry.get("retry_window_class").and_then(Value::as_str),
        Some("long")
    );
    assert_eq!(
        retry.get("readiness_state").and_then(Value::as_str),
        Some("manual_gate_pending")
    );
    assert_eq!(
        retry.get("readiness_reason").and_then(Value::as_str),
        Some("input_adjustment_required")
    );
    assert_eq!(
        retry.get("automation_safe").and_then(Value::as_bool),
        Some(false)
    );
    assert_eq!(
        retry
            .pointer("/decision_vector/next_action_after_seconds")
            .and_then(Value::as_i64),
        retry.get("next_action_after_seconds").and_then(Value::as_i64)
    );
    assert_eq!(
        retry
            .pointer("/decision_vector/next_action_kind")
            .and_then(Value::as_str),
        retry.get("next_action_kind").and_then(Value::as_str)
    );
    assert_eq!(
        retry
            .pointer("/decision_vector/readiness_reason")
            .and_then(Value::as_str),
        retry.get("readiness_reason").and_then(Value::as_str)
    );
    assert_eq!(
        retry
            .pointer("/decision_vector/automation_safe")
            .and_then(Value::as_bool),
        retry.get("automation_safe").and_then(Value::as_bool)
    );
    assert_eq!(
        retry
            .pointer("/decision_vector/decision_vector_key")
            .and_then(Value::as_str),
        retry.get("decision_vector_key").and_then(Value::as_str)
    );
    assert_eq!(
        retry.get("decision_vector_key").and_then(Value::as_str),
        Some("manual_gate|long|manual_gate_pending|input_adjustment_required|0|1800")
    );
    assert_eq!(
        retry.get("decision_route_hint").and_then(Value::as_str),
        Some("manual_review_lane")
    );
    assert_eq!(
        retry.get("decision_urgency_tier").and_then(Value::as_str),
        Some("manual")
    );
    assert_eq!(
        retry
            .get("decision_retry_budget_class")
            .and_then(Value::as_str),
        Some("manual_only")
    );
    assert_eq!(
        retry.get("decision_lane_token").and_then(Value::as_str),
        Some("manual_review_lane::manual")
    );
    assert_eq!(
        retry.get("decision_dispatch_mode").and_then(Value::as_str),
        Some("manual_review")
    );
    assert_eq!(
        retry
            .get("decision_manual_ack_required")
            .and_then(Value::as_bool),
        Some(true)
    );
    assert_eq!(
        retry.get("decision_execution_guard").and_then(Value::as_str),
        Some("manual_gate_guard")
    );
    assert_eq!(
        retry
            .get("decision_followup_required")
            .and_then(Value::as_bool),
        Some(true)
    );
    assert_eq!(
        retry.get("decision_vector_version").and_then(Value::as_str),
        Some("v1")
    );
    assert_eq!(
        retry
            .pointer("/decision_vector/route_hint")
            .and_then(Value::as_str),
        retry.get("decision_route_hint").and_then(Value::as_str)
    );
    assert_eq!(
        retry
            .pointer("/decision_vector/urgency_tier")
            .and_then(Value::as_str),
        retry.get("decision_urgency_tier").and_then(Value::as_str)
    );
    assert_eq!(
        retry
            .pointer("/decision_vector/retry_budget_class")
            .and_then(Value::as_str),
        retry
            .get("decision_retry_budget_class")
            .and_then(Value::as_str)
    );
    assert_eq!(
        retry
            .pointer("/decision_vector/lane_token")
            .and_then(Value::as_str),
        retry.get("decision_lane_token").and_then(Value::as_str)
    );
    assert_eq!(
        retry
            .pointer("/decision_vector/dispatch_mode")
            .and_then(Value::as_str),
        retry.get("decision_dispatch_mode").and_then(Value::as_str)
    );
    assert_eq!(
        retry
            .pointer("/decision_vector/manual_ack_required")
            .and_then(Value::as_bool),
        retry
            .get("decision_manual_ack_required")
            .and_then(Value::as_bool)
    );
    assert_eq!(
        retry
            .pointer("/decision_vector/execution_guard")
            .and_then(Value::as_str),
        retry.get("decision_execution_guard").and_then(Value::as_str)
    );
    assert_eq!(
        retry
            .pointer("/decision_vector/followup_required")
            .and_then(Value::as_bool),
        retry
            .get("decision_followup_required")
            .and_then(Value::as_bool)
    );
    assert_eq!(
        retry
            .pointer("/decision_vector/decision_vector_version")
            .and_then(Value::as_str),
        retry.get("decision_vector_version").and_then(Value::as_str)
    );
    assert_eq!(retry.get("retryable").and_then(Value::as_bool), Some(true));
    assert_eq!(retry.get("idempotent").and_then(Value::as_bool), Some(true));
    assert_eq!(
        retry.get("category").and_then(Value::as_str),
        Some("validation")
    );
    assert_eq!(retry.get("lane").and_then(Value::as_str), Some("web_search"));
}
