
#[test]
fn fetch_retry_envelope_runtime_helper_pins_contract_and_reason() {
    let retry = fetch_retry_envelope_runtime(
        "change_query_or_provider",
        "web_fetch_duplicate_attempt_suppressed",
        "web_fetch",
        15,
    );
    assert_eq!(
        retry.get("strategy").and_then(Value::as_str),
        Some("change_query_or_provider")
    );
    assert_eq!(
        retry.get("reason").and_then(Value::as_str),
        Some("web_fetch_duplicate_attempt_suppressed")
    );
    assert_eq!(
        retry.get("contract_version").and_then(Value::as_str),
        Some("v1")
    );
    assert_eq!(
        retry.get("contract_family").and_then(Value::as_str),
        Some("web_retry_contract_v1")
    );
    assert_eq!(
        retry.get("recovery_mode").and_then(Value::as_str),
        Some("adjust_query_or_provider")
    );
    assert_eq!(
        retry.get("priority").and_then(Value::as_str),
        Some("medium")
    );
    assert_eq!(
        retry.get("operator_action_hint").and_then(Value::as_str),
        Some("adjust_query_or_wait_for_retry_window")
    );
    assert_eq!(
        retry.get("operator_owner").and_then(Value::as_str),
        Some("system_operator")
    );
    assert_eq!(
        retry.get("diagnostic_code").and_then(Value::as_str),
        Some("fetch_retry_duplicate_attempt_suppressed")
    );
    assert_eq!(
        retry.get("blocking_kind").and_then(Value::as_str),
        Some("cooldown_required")
    );
    assert_eq!(
        retry.get("auto_retry_allowed").and_then(Value::as_bool),
        Some(true)
    );
    assert_eq!(
        retry.get("escalation_lane").and_then(Value::as_str),
        Some("automation")
    );
    assert_eq!(
        retry
            .get("requires_manual_confirmation")
            .and_then(Value::as_bool),
        Some(false)
    );
    assert_eq!(
        retry.get("execution_policy").and_then(Value::as_str),
        Some("deferred_auto_retry")
    );
    assert_eq!(
        retry.get("manual_gate_reason").and_then(Value::as_str),
        Some("none")
    );
    assert_eq!(
        retry.get("requeue_strategy").and_then(Value::as_str),
        Some("deferred")
    );
    assert_eq!(
        retry.get("can_execute_without_human").and_then(Value::as_bool),
        Some(true)
    );
    assert_eq!(
        retry.get("execution_window").and_then(Value::as_str),
        Some("after_retry_after")
    );
    assert_eq!(
        retry
            .get("manual_gate_timeout_seconds")
            .and_then(Value::as_i64),
        Some(0)
    );
    assert_eq!(
        retry.get("next_action_after_seconds").and_then(Value::as_i64),
        Some(15)
    );
    assert_eq!(
        retry.get("next_action_kind").and_then(Value::as_str),
        Some("deferred_retry")
    );
    assert_eq!(
        retry.get("retry_window_class").and_then(Value::as_str),
        Some("short")
    );
    assert_eq!(
        retry.get("readiness_state").and_then(Value::as_str),
        Some("deferred_retry_pending")
    );
    assert_eq!(
        retry.get("readiness_reason").and_then(Value::as_str),
        Some("retry_after_pending")
    );
    assert_eq!(
        retry.get("automation_safe").and_then(Value::as_bool),
        Some(true)
    );
    assert_eq!(
        retry
            .pointer("/decision_vector/next_action_after_seconds")
            .and_then(Value::as_i64),
        retry.get("next_action_after_seconds").and_then(Value::as_i64)
    );
    assert_eq!(
        retry
            .pointer("/decision_vector/next_action_kind")
            .and_then(Value::as_str),
        retry.get("next_action_kind").and_then(Value::as_str)
    );
    assert_eq!(
        retry
            .pointer("/decision_vector/readiness_reason")
            .and_then(Value::as_str),
        retry.get("readiness_reason").and_then(Value::as_str)
    );
    assert_eq!(
        retry
            .pointer("/decision_vector/automation_safe")
            .and_then(Value::as_bool),
        retry.get("automation_safe").and_then(Value::as_bool)
    );
    assert_eq!(
        retry
            .pointer("/decision_vector/decision_vector_key")
            .and_then(Value::as_str),
        retry.get("decision_vector_key").and_then(Value::as_str)
    );
    assert_eq!(
        retry.get("decision_vector_key").and_then(Value::as_str),
        Some("deferred_retry|short|deferred_retry_pending|retry_after_pending|1|15")
    );
    assert_eq!(
        retry.get("decision_route_hint").and_then(Value::as_str),
        Some("deferred_retry_lane")
    );
    assert_eq!(
        retry.get("decision_urgency_tier").and_then(Value::as_str),
        Some("medium")
    );
    assert_eq!(
        retry
            .get("decision_retry_budget_class")
            .and_then(Value::as_str),
        Some("bounded_backoff_short")
    );
    assert_eq!(
        retry.get("decision_lane_token").and_then(Value::as_str),
        Some("deferred_retry_lane::medium")
    );
    assert_eq!(
        retry.get("decision_dispatch_mode").and_then(Value::as_str),
        Some("scheduled_retry")
    );
    assert_eq!(
        retry
            .get("decision_manual_ack_required")
            .and_then(Value::as_bool),
        Some(false)
    );
    assert_eq!(
        retry.get("decision_execution_guard").and_then(Value::as_str),
        Some("retry_window_guard")
    );
    assert_eq!(
        retry
            .get("decision_followup_required")
            .and_then(Value::as_bool),
        Some(true)
    );
    assert_eq!(
        retry.get("decision_vector_version").and_then(Value::as_str),
        Some("v1")
    );
    assert_eq!(
        retry
            .pointer("/decision_vector/route_hint")
            .and_then(Value::as_str),
        retry.get("decision_route_hint").and_then(Value::as_str)
    );
    assert_eq!(
        retry
            .pointer("/decision_vector/urgency_tier")
            .and_then(Value::as_str),
        retry.get("decision_urgency_tier").and_then(Value::as_str)
    );
    assert_eq!(
        retry
            .pointer("/decision_vector/retry_budget_class")
            .and_then(Value::as_str),
        retry
            .get("decision_retry_budget_class")
            .and_then(Value::as_str)
    );
    assert_eq!(
        retry
            .pointer("/decision_vector/lane_token")
            .and_then(Value::as_str),
        retry.get("decision_lane_token").and_then(Value::as_str)
    );
    assert_eq!(
        retry
            .pointer("/decision_vector/dispatch_mode")
            .and_then(Value::as_str),
        retry.get("decision_dispatch_mode").and_then(Value::as_str)
    );
    assert_eq!(
        retry
            .pointer("/decision_vector/manual_ack_required")
            .and_then(Value::as_bool),
        retry
            .get("decision_manual_ack_required")
            .and_then(Value::as_bool)
    );
    assert_eq!(
        retry
            .pointer("/decision_vector/execution_guard")
            .and_then(Value::as_str),
        retry.get("decision_execution_guard").and_then(Value::as_str)
    );
    assert_eq!(
        retry
            .pointer("/decision_vector/followup_required")
            .and_then(Value::as_bool),
        retry
            .get("decision_followup_required")
            .and_then(Value::as_bool)
    );
    assert_eq!(
        retry
            .pointer("/decision_vector/decision_vector_version")
            .and_then(Value::as_str),
        retry.get("decision_vector_version").and_then(Value::as_str)
    );
    assert_eq!(
        retry.get("retry_after_seconds").and_then(Value::as_i64),
        Some(15)
    );
    assert_eq!(retry.get("retryable").and_then(Value::as_bool), Some(true));
    assert_eq!(retry.get("idempotent").and_then(Value::as_bool), Some(true));
    assert_eq!(
        retry.get("category").and_then(Value::as_str),
        Some("execution")
    );
    assert_eq!(retry.get("lane").and_then(Value::as_str), Some("web_fetch"));
}
